# Generated by Django 5.1.4 on 2025-06-18 09:17

import global_popup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupDesktop',
            fields=[
                ('id', models.BigIntegerField(default=global_popup.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popup_desktop_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PopupMobile',
            fields=[
                ('id', models.BigIntegerField(default=global_popup.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popup_mobile_images/')),
            ],
        ),
    ]
