# Generated by Django 5.1.4 on 2025-06-18 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_popup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='popupdesktop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='show_for_anonymous_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='show_for_logged_in_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='popupdesktop',
            name='viewing_condition',
            field=models.CharField(choices=[('once', 'Once per user'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('always', 'Always show')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='show_for_anonymous_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='show_for_logged_in_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='viewing_condition',
            field=models.CharField(choices=[('once', 'Once per user'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('always', 'Always show')], default='once', max_length=20),
        ),
        migrations.CreateModel(
            name='PopupView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('popup_desktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='global_popup.popupdesktop')),
                ('popup_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='global_popup.popupmobile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('popup_desktop', 'session_key'), ('popup_desktop', 'user'), ('popup_mobile', 'session_key'), ('popup_mobile', 'user')},
            },
        ),
    ]
