# Generated by Django 5.1.4 on 2025-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_popup', '0002_popupdesktop_created_at_popupdesktop_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupdesktop',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
