# Generated by Django 5.1.4 on 2025-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_popup', '0003_popupdesktop_link_popupmobile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupdesktop',
            name='open_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popupmobile',
            name='open_external',
            field=models.BooleanField(default=False),
        ),
    ]
