# Generated by Django 5.0 on 2026-06-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_popup', '0004_popupdesktop_open_external_popupmobile_open_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupMobileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, default='', help_text='Division / State (e.g. Dhaka). Blank = any division.', max_length=128)),
                ('city', models.CharField(blank=True, default='', help_text='City / District. Blank = any city.', max_length=128)),
                ('area', models.CharField(blank=True, default='', help_text='Area / Upazila. Blank = any area.', max_length=128)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='global_popup.popupmobile')),
            ],
            options={
                'verbose_name': 'Target location',
                'verbose_name_plural': 'Target locations',
            },
        ),
    ]
