# Generated by Django 5.0 on 2026-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='shurjopay', max_length=32)),
                ('invoice_no', models.CharField(max_length=190)),
                ('account_id', models.CharField(blank=True, default='', max_length=64)),
                ('balance_id', models.CharField(blank=True, default='', help_text='The Balance row this payment created, once it exists.', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'processed payment',
                'verbose_name_plural': 'processed payments',
                'indexes': [models.Index(fields=['account_id', '-created_at'], name='paid_account_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='processedpayment',
            constraint=models.UniqueConstraint(fields=('provider', 'invoice_no'), name='uniq_processed_payment_provider_invoice'),
        ),
    ]
