export const usePlans = () => {
  const plans = [
    {
      id: 1,
      title: 'Solar Water Purifier Micro-Business',
      poster: {
        id: 101,
        name: 'Nusrat Jahan',
        profession: 'Founder, CleanTech',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=60',
        is_pro: true,
        kyc: true,
      },
      summary: 'Low-cost solar purification units with local distribution partners. Seeking seed capital + impact donations.',
      sector: 'CleanTech',
      location: 'Rajshahi',
      city: 'Rajshahi',
      area: 'Boalia',
      stage: 'Seed',
      stageColor: 'purple',
      fundingType: 'Investment + Donation',
      minInvestment: 10000,
      expectedReturn: '12-18% (est.)',
      riskLevel: 'Medium',
      traction: '120 pre-orders',
      raised: 38500,
      goal: 120000,
      thumbnail: 'https://images.unsplash.com/photo-1509395062183-67c5ad6faff9?auto=format&fit=crop&w=1200&q=60',
      videoEmbedUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ',
      details: {
        overview: 'We will manufacture solar purifier units and sell through local agents. Donations will subsidize units for ultra-low-income families while investment funds production capacity.',
        useOfFunds: [
          'Production tooling & materials (first 200 units)',
          'Local agent onboarding and sales training',
          'Quality testing and warranty support',
        ],
        milestones: [
          'Month 1: Build 50 units + pilot sales',
          'Month 2-3: Expand to 5 unions + 200 units',
          'Month 4: Break-even target and scale plan',
        ],
      },
    },
    {
      id: 2,
      title: 'Micro-Clinic: Affordable Health Checkups',
      poster: {
        id: 102,
        name: 'Rafi Hasan',
        profession: 'Founder, HealthTech',
        avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=256&q=60',
        is_pro: false,
        kyc: true,
      },
      summary: 'A subscription-based micro-clinic model for low-income areas. Looking for investors to scale 3 locations.',
      sector: 'HealthTech',
      location: 'Dhaka',
      city: 'Dhaka',
      area: 'Mirpur',
      stage: 'Growth',
      stageColor: 'blue',
      fundingType: 'Investment',
      minInvestment: 25000,
      expectedReturn: '20-28% (est.)',
      riskLevel: 'Low',
      traction: '1,800 members',
      raised: 76000,
      goal: 250000,
      thumbnail: 'https://images.unsplash.com/photo-1580281657527-47f249e8f33a?auto=format&fit=crop&w=1200&q=60',
      videoEmbedUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
      details: {
        overview: 'Our micro-clinic provides basic health checkups at affordable rates through a subscription model.',
        useOfFunds: [
          'Equipment for 3 new clinic locations',
          'Staff training and certification',
          'Marketing and patient acquisition',
        ],
        milestones: [
          'Q1: Open 2 new locations',
          'Q2: Reach 5,000 subscribers',
          'Q3: Break-even on all locations',
        ],
      },
    },
    {
      id: 3,
      title: 'Skill Hub: Youth Training & Job Placement',
      poster: {
        id: 103,
        name: 'Mahmudul Islam',
        profession: 'Program Coordinator, EdTech',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=60',
        is_pro: true,
        kyc: false,
      },
      summary: 'Training youth on digital skills and connecting to jobs. Donations help sponsor courses; investors help expand.',
      sector: 'EdTech',
      location: 'Chattogram',
      city: 'Chattogram',
      area: 'Agrabad',
      stage: 'Early',
      stageColor: 'purple',
      fundingType: 'Donation + Revenue-share',
      minInvestment: 5000,
      expectedReturn: 'Revenue-share',
      riskLevel: 'High',
      traction: '320 learners',
      raised: 24500,
      goal: 90000,
      thumbnail: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=60',
      videoEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      details: {
        overview: 'We provide digital skills training to unemployed youth and connect them with job opportunities.',
        useOfFunds: [
          'Training materials and equipment',
          'Instructor salaries and training',
          'Job placement program development',
        ],
        milestones: [
          'Month 1-2: Train 100 students',
          'Month 3-4: Place 80% in jobs',
          'Month 5-6: Expand to 2 new cities',
        ],
      },
    },
  ]

  return {
    plans: readonly(ref(plans))
  }
}
