# Generated by Django 5.0 on 2026-06-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Office display name, e.g. "Dhaka Zonal Office".', max_length=120)),
                ('city', models.CharField(help_text="Zone city — must match users' City value (e.g. Dhaka).", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text="The officer's AdsyClub account — they log in at /zoneadmin with it.", on_delete=django.db.models.deletion.CASCADE, related_name='zonal_office', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zonal Office',
                'verbose_name_plural': 'Zonal Offices',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='ZoneFeatureCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('registration', 'User Registration (leads)'), ('pro_subscription', 'Pro Subscription'), ('microgig_post', 'MicroGig Post'), ('eshop_order', 'eShop Order'), ('mobile_recharge', 'Mobile Recharge')], max_length=32)),
                ('percent', models.DecimalField(decimal_places=2, default=0, help_text="Commission % on this feature's revenue in the zone.", max_digits=5)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zone Feature Commission',
                'verbose_name_plural': 'Zone Feature Commissions',
                'unique_together': {('office', 'feature')},
            },
        ),
    ]
