# Generated by Django 5.0 on 2026-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonefeaturecommission',
            name='percent',
        ),
        migrations.AddField(
            model_name='zonefeaturecommission',
            name='commission_type',
            field=models.CharField(choices=[('percent', 'Percent (%)'), ('flat', 'Flat amount (৳ per item)')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='zonefeaturecommission',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent (e.g. 10 = 10%) or flat ৳ per item, per the type.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='zonefeaturecommission',
            name='feature',
            field=models.CharField(choices=[('registration', 'User Registration (leads)'), ('pro_subscription', 'Pro Subscription'), ('microgig_post', 'MicroGig Post'), ('eshop_order', 'eShop Order'), ('mobile_recharge', 'Mobile Recharge'), ('gold_sponsor', 'Gold Sponsor'), ('rideshare_driver', 'Rideshare Driver Commission')], max_length=32),
        ),
    ]
