# Generated by Django 5.0 on 2026-06-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonal', '0002_remove_zonefeaturecommission_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('area', models.CharField(help_text="Upazila/area name — must match users' Upazila value.", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_managers', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Area Manager',
                'verbose_name_plural': 'Area Managers',
                'ordering': ['area'],
                'unique_together': {('office', 'area', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ZonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zonal Note',
                'verbose_name_plural': 'Zonal Notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ZonalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zonal/notices/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(blank=True, help_text='Empty = every zone sees it; set = only that zone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zonal Notice',
                'verbose_name_plural': 'Zonal Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AreaManagerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('registration', 'User Registration (leads)'), ('pro_subscription', 'Pro Subscription'), ('microgig_post', 'MicroGig Post'), ('eshop_order', 'eShop Order'), ('mobile_recharge', 'Mobile Recharge'), ('gold_sponsor', 'Gold Sponsor'), ('rideshare_driver', 'Rideshare Driver Commission')], max_length=32)),
                ('commission_type', models.CharField(choices=[('percent', 'Percent (%)'), ('flat', 'Flat amount (৳ per item)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='zonal.areamanager')),
            ],
            options={
                'verbose_name': 'Area Manager Commission',
                'verbose_name_plural': 'Area Manager Commissions',
                'unique_together': {('manager', 'feature')},
            },
        ),
    ]
