# Generated by Django 5.0 on 2026-06-11 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonal', '0003_areamanager_zonalnote_zonalnotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaloffice',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='nid_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_account_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_bank_branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='zonaloffice',
            name='payout_routing_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='ZonalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, default='', max_length=30)),
                ('trx_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Transaction ID')),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zonal Payment',
                'verbose_name_plural': 'Zonal Payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
