# Generated by Django 5.0 on 2026-06-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonal', '0004_zonaloffice_contact_phone_zonaloffice_nid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamanager',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='areamanager',
            name='payout_account_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='areamanager',
            name='payout_bank_branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='areamanager',
            name='payout_bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='areamanager',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AreaManagerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('pay_method', models.CharField(blank=True, default='', max_length=30)),
                ('pay_trx_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Transaction ID')),
                ('pay_note', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='zonal.areamanager')),
            ],
            options={
                'verbose_name': 'Area Manager Invoice',
                'verbose_name_plural': 'Area Manager Invoices',
                'ordering': ['-period_year', '-period_month'],
                'abstract': False,
                'unique_together': {('manager', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='ZonalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('pay_method', models.CharField(blank=True, default='', max_length=30)),
                ('pay_trx_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Transaction ID')),
                ('pay_note', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zonal Invoice',
                'verbose_name_plural': 'Zonal Invoices',
                'ordering': ['-period_year', '-period_month'],
                'abstract': False,
                'unique_together': {('office', 'period_year', 'period_month')},
            },
        ),
    ]
