# Generated by Django 5.0 on 2026-06-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonal', '0005_areamanager_payout_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManagerRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('registration', 'User Registration (leads)'), ('pro_subscription', 'Pro Subscription'), ('microgig_post', 'MicroGig Post'), ('eshop_order', 'eShop Order'), ('mobile_recharge', 'Mobile Recharge'), ('gold_sponsor', 'Gold Sponsor'), ('rideshare_driver', 'Rideshare Driver Commission')], max_length=32)),
                ('commission_type', models.CharField(choices=[('percent', 'Percent (%)'), ('flat', 'Flat amount (৳ per item)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='zonal.areamanager')),
            ],
            options={
                'verbose_name': 'Area Manager Rate Change',
                'verbose_name_plural': 'Area Manager Rate Changes (history)',
                'ordering': ['effective_from'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('registration', 'User Registration (leads)'), ('pro_subscription', 'Pro Subscription'), ('microgig_post', 'MicroGig Post'), ('eshop_order', 'eShop Order'), ('mobile_recharge', 'Mobile Recharge'), ('gold_sponsor', 'Gold Sponsor'), ('rideshare_driver', 'Rideshare Driver Commission')], max_length=32)),
                ('commission_type', models.CharField(choices=[('percent', 'Percent (%)'), ('flat', 'Flat amount (৳ per item)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='zonal.zonaloffice')),
            ],
            options={
                'verbose_name': 'Zone Rate Change',
                'verbose_name_plural': 'Zone Rate Changes (history)',
                'ordering': ['effective_from'],
                'abstract': False,
            },
        ),
    ]
