# Generated by Django 5.1.4 on 2025-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tipsandsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsandsuggestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
