# Generated by Django 5.1.4 on 2025-04-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tipsandsuggestion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmedia',
            name='post',
        ),
        migrations.AddField(
            model_name='newspost',
            name='medias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newsmedia'),
        ),
    ]
