# Generated by Django 5.1.4 on 2025-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsmedia_post_newspost_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='medias',
        ),
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/'),
        ),
        migrations.DeleteModel(
            name='NewsMedia',
        ),
    ]
