# Generated by Django 5.1.4 on 2025-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory_remove_newspost_medias_newspost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ManyToManyField(related_name='news_posts', to='news.newscategory'),
        ),
        migrations.DeleteModel(
            name='NewsPostTag',
        ),
    ]
