# Generated by Django 5.1.4 on 2025-04-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_content'),
        ('news', '0006_newspost_category_delete_newsposttag'),
    ]

    operations = [
    ]
