# Generated by Django 5.1.4 on 2025-05-04 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_breakingnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakingnews',
            name='description',
        ),
        migrations.AddField(
            model_name='breakingnews',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='breaking_news', to='news.newspost'),
            preserve_default=False,
        ),
    ]
