# Generated by Django 5.1.4 on 2025-05-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_breakingnews_description_breakingnews_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaking_news', to='news.newspost'),
        ),
    ]
