# Generated by Django 5.1.4 on 2026-06-12 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_name', models.CharField(blank=True, default='', max_length=200)),
                ('donor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('donor_phone', models.CharField(blank=True, default='', max_length=40)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('sp_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alliance donation',
                'verbose_name_plural': 'Alliance donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', help_text='e.g. telecom, fintech, investor, csr', max_length=80)),
                ('company', models.CharField(max_length=200)),
                ('to_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField(help_text='Main message body (HTML). Signature/contact/donate/unsubscribe added automatically.')),
                ('notes', models.CharField(blank=True, default='', help_text='Internal: why relevant / source of the email', max_length=400)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outreach draft',
                'verbose_name_plural': 'Outreach drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
