# Generated by Django 5.0 on 2026-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancedonation',
            name='language',
            field=models.CharField(default='en', help_text='Language of the donation page this came from (en/bn)', max_length=5),
        ),
        migrations.AddField(
            model_name='alliancedonation',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='Name shown on the personalized donate link (from the outreach draft)', max_length=200),
        ),
        migrations.AddField(
            model_name='outreachdraft',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text="Drives the email chrome + the recipient's donation page language", max_length=5),
        ),
    ]
