"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!fhx-*zsy791frr7y538j7bt5mx_*5pr@*inb$w!bxzszqs0^-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'base.User'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'tinymce',
    'rest_framework',
    'rest_framework.authtoken',    'cities',
    'cities_light',
    'mobile_recharge',
    'subscription',    'business_network',
    'elearning',
    'news',
    'sale',  # Add the sale app here
    'global_popup',  # Global popup system
    'support',  # Support ticket system
    'reviews',  # Reviews system
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

CORS_ALLOWED_ORIGINS = [
    'https://localhost',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://adsyclub.com',
    'https://adsyclub.com',
    'http://www.adsyclub.com',
    'https://www.adsyclub.com'
]
CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://adsyclub.com',
    'https://adsyclub.com',
    'http://www.adsyclub.com',
    'https://www.adsyclub.com'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "TOKEN_OBTAIN_SERIALIZER": "base.serializers.MyTokenObtainPairSerializer",
}

# Session settings to prevent automatic logout
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days (same as JWT tokens)
# Keep session even after browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JS access to session cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Add whitenoise middleware right after security middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow Unicode URLs (for Bangla slugs)
APPEND_SLASH = True
ALLOW_UNICODE_SLUGS = True

# Whitenoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_SERVE_MANIFEST = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'adsyclub',
        'USER': 'postgres',
        'PASSWORD': 'pgPass7431',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Force Django to serve admin static files correctly
STATIC_URL = '/static/'
STATICFILES_DIRS = []  # Empty to avoid conflicts

# Make sure static root is clearly defined
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Make sure admin files are included even in production
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise configuration for serving static files
WHITENOISE_USE_FINDERS = True
WHITENOISE_ROOT = STATIC_ROOT
WHITENOISE_INDEX_FILE = True
WHITENOISE_MANIFEST_STRICT = False

# This enables compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'https://adsyclub.com/media/'
# MEDIA_URL = 'http://127.0.0.1:8000//media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Increase max upload size to 50MB (default is around 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BEAT_SCHEDULE = {
    'auto-approve-tasks': {
        'task': 'base.tasks.check_and_auto_approve_tasks',
        'schedule': timedelta(minutes=30),  # Run every 30 minutes
    },
    'deactivate-expired-subscriptions': {
        'task': 'subscription.tasks.deactivate_expired_subscriptions',
        'schedule': timedelta(days=1),  # Run once every day
    },
}

# ShurjoPay Settings
SP_USERNAME = "lyriczsoft"
SP_PASSWORD = "lyrikskdzprvz&ud"
SP_ENDPOINT = "https://engine.shurjopayment.com"
SP_RETURN = "https://adsyclub.com/verify-payment"
SP_CANCEL = "https://adsyclub.com/deposit-withdraw/"
SP_PREFIX = "ADSYCLUB_"
API_SMS = 'SplZ3f60tlt69pkZAEc8WHk3MbHkGeLYtJ1jElCd'

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'plugins': [
        'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
        'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
        'insertdatetime', 'media', 'table', 'paste', 'help', 'wordcount'
    ],
    'toolbar': 'undo redo | blocks | '
               'bold italic forecolor | alignleft aligncenter '
               'alignright alignjustify | bullist numlist outdent indent | '
               'removeformat | help',
    'content_css': 'default',
    'height': 400,
    'width': 'auto',
    'resize': True,
    'statusbar': True,
    'branding': False,
    'elementpath': True,
    'paste_data_images': True,
    'paste_as_text': False,
    'paste_remove_styles_if_webkit': True,
    'verify_html': False,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'skin': 'oxide',
    'content_style': '''
        body { 
            font-family: -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif; 
            font-size: 14px; 
            line-height: 1.4; 
        }
        p { margin: 0 0 10px 0; }
    ''',
    'block_formats': 'Paragraph=p; Header 1=h1; Header 2=h2; Header 3=h3; Header 4=h4; Header 5=h5; Header 6=h6;',
    'font_formats': '''
        Andale Mono=andale mono,times; 
        Arial=arial,helvetica,sans-serif; 
        Arial Black=arial black,avant garde; 
        Book Antiqua=book antiqua,palatino; 
        Comic Sans MS=comic sans ms,sans-serif; 
        Courier New=courier new,courier; 
        Georgia=georgia,palatino; 
        Helvetica=helvetica; 
        Impact=impact,chicago; 
        Symbol=symbol; 
        Tahoma=tahoma,arial,helvetica,sans-serif; 
        Terminal=terminal,monaco; 
        Times New Roman=times new roman,times; 
        Trebuchet MS=trebuchet ms,geneva; 
        Verdana=verdana,geneva; 
        Webdings=webdings; 
        Wingdings=wingdings,zapf dingbats
    ''',
}
