"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}nformation on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (if present) so local dev can
# flip DEBUG/CORS without touching settings.py. Safe no-op in prod where
# the file is absent and real env vars are injected by the platform.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!fhx-*zsy791frr7y538j7bt5mx_*5pr@*inb$w!bxzszqs0^-"

# SECURITY WARNING: don't run with debug turned on in production!
# Driven by env var so production turns DEBUG OFF automatically.
# DEBUG=True adds ~2-3s latency per request (full query logging, verbose errors).
DEBUG = os.getenv("DEBUG", "false").lower() in ("true", "1", "yes", "on")

_local_hosts = ["localhost", "127.0.0.1", "10.0.2.2"]
_prod_hosts = ["adsyclub.com", "www.adsyclub.com"]
# Loopback addresses are always safe — they are unreachable from the internet.
ALLOWED_HOSTS = _prod_hosts + _local_hosts
AUTH_USER_MODEL = "base.User"


# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "base",
    "tinymce",
    "rest_framework",
    "rest_framework.authtoken",
    "cities",
    "cities_light",
    "mobile_recharge",
    "subscription",
    "business_network",
    "elearning",
    "news",
    "sale",  # Add the sale app here
    "global_popup",  # Global popup system
    "support",  # Support ticket system
    "reviews",  # Reviews system
    "adsyconnect",  # AdsyConnect chat system
    "workspace",  # Workspace gigs system
    "referral_rewards",  # New Year referral reward program
    "raise_up",  # Raise Up crowdfunding system
    "rideshare",  # Ride share MVP
    "app_versioning",  # Mobile app update prompts
    "engagement",  # Engagement & assistant brain (event tracking + user state)
    "django_filters",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_celery_beat",  # For Celery Beat database scheduler
]


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")

CORS_ALLOWED_ORIGINS = [
    "https://adsyclub.com",
    "https://www.adsyclub.com",
]

# CORS settings for API access
CORS_ALLOW_CREDENTIALS = True
# Allow all origins in DEBUG so local dev servers (Flutter web, Nuxt) aren't blocked.
# Production keeps strict origin allowlist.
# Allow all origins when DEBUG or when request comes from localhost.
# Production Cloudflare proxy always sends the real domain as Origin anyway.
# Production=False (strict). Override with CORS_ALLOW_ALL_ORIGINS=true env var
# for local dev when .env loading is unavailable.
_cors_allow_all_env = os.getenv("CORS_ALLOW_ALL_ORIGINS", "").lower()
CORS_ALLOW_ALL_ORIGINS = DEBUG or (_cors_allow_all_env in ("true", "1"))
CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "cache-control",
    "pragma",
]

CSRF_TRUSTED_ORIGINS = [
    "https://adsyclub.com",
    "https://www.adsyclub.com",
]

# CSRF settings for API compatibility
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    # Always attach a clean, human-readable `message` to API errors so the app
    # never shows a raw serializer dump / exception code.
    "EXCEPTION_HANDLER": "base.error_utils.custom_exception_handler",
}
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "TOKEN_OBTAIN_SERIALIZER": "base.serializers.MyTokenObtainPairSerializer",
}

# Session settings to prevent automatic logout
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days (same as JWT tokens)
# Keep session even after browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# NOTE: SESSION_SAVE_EVERY_REQUEST removed — was causing a DB UPDATE on the
# django_session table for EVERY request (~100-300ms per request, plus write
# contention under load). Sessions are auto-refreshed by SessionMiddleware
# when actually modified; the explicit save was redundant.
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JS access to session cookie
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection

MIDDLEWARE = [
    "base.middleware.BlockConnectMethodMiddleware",  # Block HTTP CONNECT proxy requests
    "base.middleware.AccountSuspendedMiddleware",  # 403 every service API for suspended users
    "django.middleware.security.SecurityMiddleware",
    "backend.https_redirect_middleware.CloudflareHttpsRedirectMiddleware",
    # Add whitenoise middleware right after security middleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "backend.csrf_exempt_middleware_clean.CSRFExemptMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Allow Unicode URLs (for Bangla slugs)
APPEND_SLASH = True
ALLOW_UNICODE_SLUGS = True

# Whitenoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_SERVE_MANIFEST = True

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "frontend/dist"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYER_BACKEND = os.getenv("CHANNEL_LAYER_BACKEND", "").lower()

if not CHANNEL_LAYER_BACKEND:
    # Auto-detect: try Redis, fall back to in-memory for local dev
    import socket as _socket
    _redis_url = os.getenv("CHANNEL_REDIS_URL", "redis://127.0.0.1:6379/1")
    try:
        _s = _socket.create_connection(("127.0.0.1", 6379), timeout=0.5)
        _s.close()
        CHANNEL_LAYER_BACKEND = "redis"
    except OSError:
        CHANNEL_LAYER_BACKEND = "memory"

if CHANNEL_LAYER_BACKEND == "redis":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.getenv("CHANNEL_REDIS_URL", "redis://127.0.0.1:6379/1")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "adsyclub",
        "USER": "postgres",
        "PASSWORD": "pgPass7431",
        "HOST": "localhost",
        "PORT": "5432",
        # Reuse Postgres connections across requests instead of opening a new
        # one for every API call (saved ~50-100ms per request). Health check
        # ensures stale connections are replaced.
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Force Django to serve admin static files correctly
STATIC_URL = "/static/"
STATICFILES_DIRS = []  # Empty to avoid conflicts

# Make sure static root is clearly defined
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Make sure admin files are included even in production
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# WhiteNoise configuration for serving static files
WHITENOISE_USE_FINDERS = True
WHITENOISE_ROOT = STATIC_ROOT
WHITENOISE_INDEX_FILE = True
WHITENOISE_MANIFEST_STRICT = False

# This enables compression and caching
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Optional Cloudflare R2 media storage.
# Enable only after the R2 bucket, API token, and public/custom media domain are
# configured. Static files continue to use WhiteNoise; only user/admin uploads
# move to R2.
CLOUDFLARE_R2_MEDIA_ENABLED = _env_bool(
    "CLOUDFLARE_R2_MEDIA_ENABLED",
    _env_bool("USE_R2_MEDIA_STORAGE", False),
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

if CLOUDFLARE_R2_MEDIA_ENABLED:
    CLOUDFLARE_R2_ACCOUNT_ID = os.getenv("CLOUDFLARE_R2_ACCOUNT_ID", "").strip()
    CLOUDFLARE_R2_ACCESS_KEY_ID = os.getenv(
        "CLOUDFLARE_R2_ACCESS_KEY_ID", ""
    ).strip()
    CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.getenv(
        "CLOUDFLARE_R2_SECRET_ACCESS_KEY", ""
    ).strip()
    CLOUDFLARE_R2_BUCKET_NAME = os.getenv("CLOUDFLARE_R2_BUCKET_NAME", "").strip()
    CLOUDFLARE_R2_CUSTOM_DOMAIN = (
        os.getenv("CLOUDFLARE_R2_CUSTOM_DOMAIN", "")
        .replace("https://", "")
        .replace("http://", "")
        .strip()
        .rstrip("/")
    )
    CLOUDFLARE_R2_PUBLIC_URL = (
        os.getenv("CLOUDFLARE_R2_PUBLIC_URL", "").strip().rstrip("/")
    )
    if not CLOUDFLARE_R2_PUBLIC_URL and CLOUDFLARE_R2_CUSTOM_DOMAIN:
        CLOUDFLARE_R2_PUBLIC_URL = f"https://{CLOUDFLARE_R2_CUSTOM_DOMAIN}"

    _missing_r2_settings = [
        name
        for name, value in {
            "CLOUDFLARE_R2_ACCOUNT_ID": CLOUDFLARE_R2_ACCOUNT_ID,
            "CLOUDFLARE_R2_ACCESS_KEY_ID": CLOUDFLARE_R2_ACCESS_KEY_ID,
            "CLOUDFLARE_R2_SECRET_ACCESS_KEY": CLOUDFLARE_R2_SECRET_ACCESS_KEY,
            "CLOUDFLARE_R2_BUCKET_NAME": CLOUDFLARE_R2_BUCKET_NAME,
            "CLOUDFLARE_R2_PUBLIC_URL or CLOUDFLARE_R2_CUSTOM_DOMAIN": (
                CLOUDFLARE_R2_PUBLIC_URL
            ),
        }.items()
        if not value
    ]
    if _missing_r2_settings:
        raise ImproperlyConfigured(
            "Cloudflare R2 media storage is enabled but missing: "
            + ", ".join(_missing_r2_settings)
        )

    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS.append("storages")

    AWS_ACCESS_KEY_ID = CLOUDFLARE_R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = CLOUDFLARE_R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = CLOUDFLARE_R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = os.getenv(
        "CLOUDFLARE_R2_ENDPOINT_URL",
        f"https://{CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
    ).rstrip("/")
    AWS_S3_REGION_NAME = os.getenv("CLOUDFLARE_R2_REGION", "auto")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = _env_bool("CLOUDFLARE_R2_QUERYSTRING_AUTH", False)
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": os.getenv(
            "CLOUDFLARE_R2_CACHE_CONTROL",
            "public, max-age=31536000, immutable",
        )
    }
    AWS_S3_CUSTOM_DOMAIN = CLOUDFLARE_R2_CUSTOM_DOMAIN or None
    AWS_S3_URL_PROTOCOL = "https:"

    MEDIA_URL = f"{CLOUDFLARE_R2_PUBLIC_URL}/"
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "region_name": AWS_S3_REGION_NAME,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
            "addressing_style": AWS_S3_ADDRESSING_STYLE,
            "default_acl": AWS_DEFAULT_ACL,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
            "object_parameters": AWS_S3_OBJECT_PARAMETERS,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": AWS_S3_URL_PROTOCOL,
        },
    }

# Redis-backed cache for hot, global, low-volatility read endpoints (logo,
# auth banner, etc.). Falls back to the local Redis used by Celery/Channels.
# DB 0 = Celery, DB 1 = Channels, so cache uses DB 2 by default. KEY_PREFIX keeps
# it isolated from the other Django apps sharing this Redis instance.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("DJANGO_CACHE_REDIS_URL", "redis://127.0.0.1:6379/2"),
        "KEY_PREFIX": os.getenv("DJANGO_CACHE_KEY_PREFIX", "adsyclub"),
        "TIMEOUT": 300,
    }
}

# Increase max upload size to 1024MB (default is around 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1024MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1024MB in bytes

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RIDESHARE_ROUTE_PROVIDER = os.getenv("RIDESHARE_ROUTE_PROVIDER", "osrm")
RIDESHARE_OPENSTREET_ROUTE_URL = os.getenv("RIDESHARE_OPENSTREET_ROUTE_URL", "https://api.open-street.com/route")
RIDESHARE_OPENSTREET_ROUTE_KEY = os.getenv("RIDESHARE_OPENSTREET_ROUTE_KEY", "")
RIDESHARE_LOCATION_PROVIDER = os.getenv("RIDESHARE_LOCATION_PROVIDER", "photon")
RIDESHARE_GOOGLE_PLACES_AUTOCOMPLETE_URL = os.getenv("RIDESHARE_GOOGLE_PLACES_AUTOCOMPLETE_URL", "https://maps.googleapis.com/maps/api/place/autocomplete/json")
RIDESHARE_GOOGLE_PLACES_TEXTSEARCH_URL = os.getenv("RIDESHARE_GOOGLE_PLACES_TEXTSEARCH_URL", "https://maps.googleapis.com/maps/api/place/textsearch/json")
RIDESHARE_GOOGLE_PLACE_DETAILS_URL = os.getenv("RIDESHARE_GOOGLE_PLACE_DETAILS_URL", "https://maps.googleapis.com/maps/api/place/details/json")
RIDESHARE_GOOGLE_GEOCODE_URL = os.getenv("RIDESHARE_GOOGLE_GEOCODE_URL", "https://maps.googleapis.com/maps/api/geocode/json")
RIDESHARE_GOOGLE_MAPS_API_KEY = os.getenv("RIDESHARE_GOOGLE_MAPS_API_KEY", "")
RIDESHARE_GOOGLE_LANGUAGE = os.getenv("RIDESHARE_GOOGLE_LANGUAGE", "bn")
RIDESHARE_GOOGLE_REGION = os.getenv("RIDESHARE_GOOGLE_REGION", "bd")
RIDESHARE_PHOTON_URL = os.getenv("RIDESHARE_PHOTON_URL", "https://photon.komoot.io/api/")
RIDESHARE_PHOTON_DEFAULT_LAT = float(os.getenv("RIDESHARE_PHOTON_DEFAULT_LAT", "23.6850"))
RIDESHARE_PHOTON_DEFAULT_LNG = float(os.getenv("RIDESHARE_PHOTON_DEFAULT_LNG", "90.3563"))
RIDESHARE_OSRM_URL = os.getenv("RIDESHARE_OSRM_URL", "http://127.0.0.1:5000")
RIDESHARE_OSRM_FALLBACK_URLS = [
    url.strip()
    for url in os.getenv(
        "RIDESHARE_OSRM_FALLBACK_URLS",
        "https://router.project-osrm.org",
    ).split(",")
    if url.strip()
]
RIDESHARE_NOMINATIM_URL = os.getenv("RIDESHARE_NOMINATIM_URL", "https://nominatim.openstreetmap.org")

# iOS VoIP/APNs settings for native CallKit incoming calls.
# APNS_VOIP_TOPIC normally looks like: com.your.bundle.id.voip
APNS_AUTH_KEY_PATH = os.getenv("APNS_AUTH_KEY_PATH", "")
APNS_KEY_ID = os.getenv("APNS_KEY_ID", "")
APNS_TEAM_ID = os.getenv("APNS_TEAM_ID", "")
IOS_APP_TEAM_ID = os.getenv("IOS_APP_TEAM_ID", APNS_TEAM_ID)
APNS_VOIP_TOPIC = os.getenv("APNS_VOIP_TOPIC", "")
APNS_ENVIRONMENT = os.getenv("APNS_ENVIRONMENT", "production")

# Agora real-time audio/video call settings.
# If AGORA_APP_CERTIFICATE is empty the app continues to use Agora's no-token
# mode. When a certificate is configured, native clients must request scoped
# RTC tokens from the backend before joining a channel.
AGORA_APP_ID = os.getenv("AGORA_APP_ID", "9eba1a50633041d08dbe75b0fde2ed8a")
AGORA_APP_CERTIFICATE = os.getenv("AGORA_APP_CERTIFICATE", "")
AGORA_TOKEN_EXPIRE_SECONDS = int(os.getenv("AGORA_TOKEN_EXPIRE_SECONDS", "3600"))

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # You can change this to your Redis URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'  # Set your timezone
CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {
    "auto-approve-tasks": {
        "task": "base.tasks.check_and_auto_approve_tasks",
        "schedule": timedelta(minutes=30),  # Run every 30 minutes
    },
    "deactivate-expired-subscriptions": {
        "task": "subscription.tasks.deactivate_expired_subscriptions",
        "schedule": timedelta(minutes=10),  # Run every 10 minutes
    },
    "process-subscription-auto-renewals": {
        "task": "subscription.tasks.process_auto_renewals",
        "schedule": timedelta(hours=6),  # Charge balance / follow up on renewals
    },
    "process-gold-sponsor-lifecycle": {
        "task": "business_network.tasks.process_gold_sponsor_lifecycle",
        "schedule": timedelta(hours=6),  # Auto-renew + multi-step renewal follow-ups
    },
    "cascade-expired-ride-targets": {
        "task": "rideshare.tasks.cascade_expired_ride_targets",
        "schedule": timedelta(seconds=30),  # Run every 30 seconds to check 1-minute timeouts
    },
    "cancel-expired-rides": {
        "task": "rideshare.tasks.cancel_expired_rides",
        "schedule": timedelta(minutes=2),  # Run every 2 minutes to check 15-minute timeouts
    },
    "mark-stale-drivers-offline": {
        "task": "rideshare.tasks.mark_stale_drivers_offline",
        "schedule": timedelta(minutes=2),  # Run every 2 minutes to auto-offline stale drivers
    },
    "cleanup-stale-adsyconnect-calls": {
        "task": "adsyconnect.tasks.cleanup_stale_call_sessions",
        "schedule": timedelta(minutes=1),  # Clear stuck ringing/joining calls
    },
    "aggregate-user-engagement-states": {
        "task": "engagement.tasks.aggregate_user_states",
        "schedule": timedelta(minutes=30),  # Roll events into per-user state + lifecycle
    },
    "run-engagement-nudge-engine": {
        "task": "engagement.tasks.run_nudge_engine",
        "schedule": timedelta(hours=2),  # Pick + deliver the best nudge per user
    },
    "run-feature-promos": {
        "task": "engagement.tasks.run_feature_promos",
        "schedule": timedelta(hours=1),  # Spread ~2 feature promos/user across 9am-9pm
    },
    "run-email-engine": {
        "task": "engagement.tasks.run_email_engine",
        "schedule": timedelta(hours=6),  # helpful + activity emails, cooldown-gated per user
    },
    "run-guest-nudges": {
        "task": "engagement.tasks.run_guest_nudges",
        "schedule": timedelta(hours=12),  # registration-conversion pushes to guest devices
    },
}

# --- Engagement / assistant-brain nudge engine ---
# Master switch + guard rails. Nudges only deliver during the daytime window,
# at most one per user per day, with per-nudge cooldowns handled in code.
ENGAGEMENT_NUDGES_ENABLED = True
ENGAGEMENT_TIMEZONE = "Asia/Dhaka"        # audience timezone for the send window
ENGAGEMENT_NUDGE_HOURS = (9, 21)          # 9am-9pm in ENGAGEMENT_TIMEZONE
# Push costs nothing (FCM) — keep only a runaway safety ceiling so every
# eligible user gets their nudge in a single run.
ENGAGEMENT_NUDGE_PER_RUN_CAP = 10000
# Hold lifecycle-heuristic nudges (win-back, at-risk) until ~a week of event
# data has accumulated and the lifecycle stages are trustworthy. Flip to True
# then. Hard-data nudges (KYC withdraw, subscription, onboarding) send regardless.
ENGAGEMENT_LIFECYCLE_NUDGES_ENABLED = False

# --- Feature-awareness promos (Amar Sheba, eShop, Mindforce, Workspace,
# Rideshare, MicroGigs, News). ~N varied Bangla promos per user per day, spread
# at random times across 9am-9pm BDT, no line repeated within a week. Sent to
# every active user with a device. Flip ENABLED to False to pause instantly.
ENGAGEMENT_FEATURE_PROMOS_ENABLED = True
ENGAGEMENT_FEATURE_PROMOS_PER_DAY = 2

# --- Engagement EMAIL engine (the email counterpart of the push brain) ---
# For each user: emails the best activity nudge (verify KYC, complete profile,
# renew Pro, withdraw balance, win-back) or, if none applies, a varied helpful
# feature email with live eShop content. Independent email cooldown so it never
# collides with push. OFF by default — validate with run_email_engine(dry_run=True)
# then set True.
ENGAGEMENT_EMAIL_ENABLED = True
ENGAGEMENT_EMAIL_HOURS = (10, 20)          # 10am-8pm in ENGAGEMENT_TIMEZONE
# Our SMTP has no outbound limit, so no artificial throttle — the real
# anti-spam guard is the per-user cooldown below. The cap is only a runaway
# safety ceiling, set far above the user base.
ENGAGEMENT_EMAIL_PER_RUN_CAP = 100000
ENGAGEMENT_EMAIL_COOLDOWN_DAYS = 3         # at most one engagement email / N days / user

# --- Guest registration-conversion pushes (FCMToken.user is None) ---
# Devices that installed but didn't register get a rotating series of Bangla
# sign-up nudges (engagement/guest_promos.py), one every N days until the
# series is done. ENABLED so it starts working as soon as guest tokens are
# captured by the new app build.
GUEST_NUDGES_ENABLED = True
GUEST_NUDGE_COOLDOWN_DAYS = 1              # one guest push per device per day
GUEST_NUDGE_PER_RUN_CAP = 500             # anti-burst: max guest pushes per run
# Note: the series loops forever (one message/day, cycling) until the device
# registers — it does not stop after the 6 messages.

# ShurjoPay Settings
SP_USERNAME = "lyriczsoft"
SP_PASSWORD = "lyrikskdzprvz&ud"
SP_ENDPOINT = "https://engine.shurjopayment.com"
SP_RETURN = "https://adsyclub.com/verify-payment"
SP_CANCEL = "https://adsyclub.com/deposit-withdraw/"
SP_PREFIX = "ADSYCLUB_"

# sms settings
API_SMS = os.getenv("API_SMS", "SplZ3f60tlt69pkZAEc8WHk3MbHkGeLYtJ1jElCd")
SMS_SENDER_ID = os.getenv("SMS_SENDER_ID", "8809617626171")

# Email Configuration (SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# SMTP + addresses come from the database (Django admin → Email Settings);
# these env-driven values are only last-resort fallbacks — no emails are
# hardcoded in code.
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "AdsyClub <support@adsyclub.com>")
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "")

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    "plugins": [
        "advlist",
        "autolink",
        "lists",
        "link",
        "image",
        "charmap",
        "preview",
        "anchor",
        "searchreplace",
        "visualblocks",
        "code",
        "fullscreen",
        "insertdatetime",
        "media",
        "table",
        "paste",
        "help",
        "wordcount",
    ],
    "toolbar": "undo redo | blocks | "
    "bold italic forecolor | alignleft aligncenter "
    "alignright alignjustify | bullist numlist outdent indent | "
    "removeformat | help",
    "content_css": "default",
    "height": 400,
    "width": "auto",
    "resize": True,
    "statusbar": True,
    "branding": False,
    "elementpath": True,
    "paste_data_images": True,
    "paste_as_text": False,
    "paste_remove_styles_if_webkit": True,
    "verify_html": False,
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea",
    "theme": "silver",
    "skin": "oxide",
    "content_style": """
        body { 
            font-family: -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif; 
            font-size: 14px; 
            line-height: 1.4; 
        }
        p { margin: 0 0 10px 0; }
    """,
    "block_formats": "Paragraph=p; Header 1=h1; Header 2=h2; Header 3=h3; Header 4=h4; Header 5=h5; Header 6=h6;",
    "font_formats": """
        Andale Mono=andale mono,times; 
        Arial=arial,helvetica,sans-serif; 
        Arial Black=arial black,avant garde; 
        Book Antiqua=book antiqua,palatino; 
        Comic Sans MS=comic sans ms,sans-serif; 
        Courier New=courier new,courier; 
        Georgia=georgia,palatino; 
        Helvetica=helvetica; 
        Impact=impact,chicago; 
        Symbol=symbol; 
        Tahoma=tahoma,arial,helvetica,sans-serif; 
        Terminal=terminal,monaco; 
        Times New Roman=times new roman,times; 
        Trebuchet MS=trebuchet ms,geneva; 
        Verdana=verdana,geneva; 
        Webdings=webdings; 
        Wingdings=wingdings,zapf dingbats
    """,
}
