# Generated by Django 5.1.4 on 2025-06-01 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the popup', max_length=200)),
                ('popup_type', models.CharField(choices=[('image', 'Image Popup'), ('text', 'Text Popup'), ('mixed', 'Mixed Content')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload popup image', null=True, upload_to='popups/')),
                ('text_content', models.TextField(blank=True, help_text='Text content for the popup', null=True)),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL', null=True)),
                ('link_text', models.CharField(blank=True, help_text='Link button text', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this popup to users')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start showing this popup')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this popup (optional)', null=True)),
                ('display_frequency', models.CharField(choices=[('once', 'Show Once Per Session'), ('always', 'Show Every Visit'), ('daily', 'Show Once Per Day')], default='once', max_length=10)),
                ('show_to_authenticated_users', models.BooleanField(default=True, help_text='Show to logged-in users')),
                ('show_to_anonymous_users', models.BooleanField(default=True, help_text='Show to visitors')),
                ('delay_seconds', models.IntegerField(default=2, help_text='Delay before showing popup (in seconds)')),
                ('width', models.IntegerField(default=500, help_text='Popup width in pixels')),
                ('height', models.IntegerField(default=400, help_text='Popup height in pixels')),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Text color (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this popup was shown')),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopupView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_views', to='popups.popup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('popup', 'user', 'session_key')},
            },
        ),
    ]
