# Generated by Django 5.1.4 on 2025-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='auto_close_delay',
            field=models.IntegerField(default=10, help_text='Auto-close delay in seconds (0 = no auto-close)'),
        ),
        migrations.AddField(
            model_name='popup',
            name='auto_close_enabled',
            field=models.BooleanField(default=True, help_text='Automatically close popup after specified time'),
        ),
        migrations.AddField(
            model_name='popup',
            name='close_on_overlay_click',
            field=models.BooleanField(default=True, help_text='Allow closing by clicking outside popup'),
        ),
        migrations.AddField(
            model_name='popup',
            name='show_close_button',
            field=models.BooleanField(default=True, help_text='Show manual close button'),
        ),
    ]
