# Generated by Django 5.1.4 on 2025-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0002_popup_auto_close_delay_popup_auto_close_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='link_navigation',
            field=models.CharField(choices=[('internal', 'Open in same window/app'), ('external', 'Open in external browser'), ('new_tab', 'Open in new tab')], default='internal', help_text='How the link should open', max_length=10),
        ),
    ]
