# Generated by Django 5.1.4 on 2025-06-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0003_popup_link_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='show_to_pro_users_only',
            field=models.BooleanField(default=False, help_text='Show only to pro/premium users'),
        ),
    ]
