# Generated by Django 5.0.1 on 2025-12-15 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseUpPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('seed', 'Seed'), ('early', 'Early'), ('growth', 'Growth')], max_length=20)),
                ('stage_color', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('emerald', 'Emerald'), ('amber', 'Amber')], max_length=20)),
                ('funding_type', models.CharField(choices=[('investment', 'Investment'), ('donation', 'Donation'), ('investment_donation', 'Investment + Donation'), ('revenue_share', 'Revenue Share')], max_length=50)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('traction', models.CharField(max_length=200)),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thumbnail', models.URLField()),
                ('video_embed_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raise_up_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaiseUpPostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('use_of_funds', models.JSONField(default=list)),
                ('milestones', models.JSONField(default=list)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='raise_up.raiseuppost')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('avatar', models.URLField(blank=True)),
                ('is_pro', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raise_up_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
