# Generated by Django 5.0.1 on 2025-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_up', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseuppost',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
    ]
