# Generated by Django 5.0.1 on 2025-12-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_up', '0003_raiseuppost_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseuppost',
            name='expected_return',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='raiseuppost',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='raiseuppost',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='raiseuppost',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='raiseuppost',
            name='video_embed_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
