# Generated by Django 5.0.1 on 2025-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_up', '0004_alter_raiseuppost_expected_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseuppost',
            name='traction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
