# Generated by Django 5.1.4 on 2025-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank_transfer', 'Bank Transfer'), ('sslcommerz', 'SSLCommerz'), ('account_balance', 'Account Balance'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
