# Generated by Django 5.1.4 on 2026-07-12 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IapProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('diamonds', 'Diamonds'), ('pro', 'Pro subscription'), ('gold', 'Gold Sponsor subscription')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('google_product_id', models.CharField(help_text='Play Console product id (e.g. adsyclub_pro, diamonds_50).', max_length=150, unique=True)),
                ('base_plan_id', models.CharField(blank=True, default='', help_text='Subscriptions only: the base plan id (e.g. monthly, yearly).', max_length=120)),
                ('is_subscription', models.BooleanField(default=False, help_text='True for Pro & Gold Sponsor (auto-renew).')),
                ('diamonds', models.PositiveIntegerField(default=0, help_text='Diamonds granted (diamonds kind).')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text="Access days for Gold Sponsor; Pro uses Google's expiry.")),
                ('price_label', models.CharField(blank=True, default='', help_text="Display price, e.g. '৳100' or '$0.99'.", max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IAP product',
                'verbose_name_plural': 'IAP products',
                'ordering': ['kind', 'sort_order', 'google_product_id'],
            },
        ),
        migrations.CreateModel(
            name='IapPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('google_product_id', models.CharField(max_length=150)),
                ('purchase_token', models.TextField(unique=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=120)),
                ('ref_id', models.CharField(blank=True, default='', help_text='Optional in-app object this purchase completes (e.g. a pending Gold Sponsor id).', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_subscription', models.BooleanField(default=False)),
                ('expiry_at', models.DateTimeField(blank=True, help_text='Subscription expiry from Google.', null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iap_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IAP purchase',
                'verbose_name_plural': 'IAP purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='iap_user_recent_idx'), models.Index(fields=['status'], name='iap_status_idx')],
            },
        ),
    ]
