# Generated by Django 5.0 on 2026-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iappurchase',
            name='obfuscated_account_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='iappurchase',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iappurchase',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
