# Generated by Django 5.1.4 on 2025-05-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='SVG code for the batch icon', max_length=500, verbose_name='Icon SVG')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='SVG code for the division icon', max_length=500, verbose_name='Icon SVG')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('batches', models.ManyToManyField(related_name='divisions', to='elearning.batch')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='SVG code for the subject icon', max_length=500, verbose_name='Icon SVG')),
                ('color', models.CharField(default='#3B82F6', help_text='Color code for the subject card', max_length=20, verbose_name='Color')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('divisions', models.ManyToManyField(related_name='subjects', to='elearning.division')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_bn', models.CharField(blank=True, max_length=200, verbose_name='Bengali Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_bn', models.TextField(blank=True, verbose_name='Bengali Description')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Lesson Name')),
                ('lesson_name_bn', models.CharField(blank=True, max_length=100, verbose_name='Bengali Lesson Name')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='elearning.subject')),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
