# Generated by Django 5.1.4 on 2025-05-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_session_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicesession',
            new_name='elearning_d_device__ac3812_idx',
            old_name='elearning_d_device__84ceaf_idx',
        ),
        migrations.RenameIndex(
            model_name='devicesession',
            new_name='elearning_d_user_id_a889b7_idx',
            old_name='elearning_d_user_id_1e86da_idx',
        ),
        migrations.RenameIndex(
            model_name='elearningsession',
            new_name='elearning_e_user_id_438b80_idx',
            old_name='elearning_e_user_id_b6c71c_idx',
        ),
        migrations.RenameIndex(
            model_name='elearningsession',
            new_name='elearning_e_device__30c9e3_idx',
            old_name='elearning_e_device__2e67eb_idx',
        ),
        migrations.RenameIndex(
            model_name='elearningsession',
            new_name='elearning_e_ip_addr_cecd9f_idx',
            old_name='elearning_e_ip_addr_9c8f31_idx',
        ),
        migrations.RenameIndex(
            model_name='elearningsession',
            new_name='elearning_e_started_b3e4f0_idx',
            old_name='elearning_e_started_5ef6ee_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionactivitylog',
            new_name='elearning_s_session_f6eb28_idx',
            old_name='elearning_s_session_c61e57_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionactivitylog',
            new_name='elearning_s_action_a3ae52_idx',
            old_name='elearning_s_action_db0628_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='elearning_s_user_id_6cedbe_idx',
            old_name='elearning_s_user_id_e85b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='elearning_s_activit_9928af_idx',
            old_name='elearning_s_activit_6da9b9_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='elearning_s_severit_2f32a8_idx',
            old_name='elearning_s_severit_f2a1e6_idx',
        ),
    ]
