# Generated by Django 5.1.4 on 2025-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('elearning', '0004_rename_elearning_d_device__84ceaf_idx_elearning_d_device__ac3812_idx_and_more'),
    ]

    operations = [
        # Drop session-related tables since we're removing session management
        migrations.RunSQL("DROP TABLE IF EXISTS elearning_sessionactivitylog CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS elearning_suspiciousactivity CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS elearning_elearningsession CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS elearning_devicesession CASCADE;"),
    ]
