# Generated by Django 5.1.4 on 2025-05-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_drop_session_tables'),
    ]

    operations = [
        # No operations needed - tables were already dropped in migration 0005
        # This migration is kept for consistency with the migration history
    ]
