# Generated by Django 5.1.4 on 2026-07-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_remove_elearningsession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningBanner',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional caption/label (for admin reference).', max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='elearning/banners/', verbose_name='Image')),
                ('link_type', models.CharField(choices=[('none', 'No link (image only)'), ('internal', 'Internal app page'), ('external', 'External website')], default='none', max_length=20, verbose_name='Link Type')),
                ('link_url', models.CharField(blank=True, help_text='Internal route (e.g. /elearning, /eshop) or external URL (https://...). Leave empty for an image-only slide.', max_length=500, verbose_name='Link')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'eLearning Banner',
                'verbose_name_plural': 'eLearning Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
