# Generated by Django 5.1.4 on 2025-05-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_drop_session_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearningsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessionactivitylog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeviceSession',
        ),
        migrations.DeleteModel(
            name='ELearningSession',
        ),
        migrations.DeleteModel(
            name='SessionActivityLog',
        ),
        migrations.DeleteModel(
            name='SuspiciousActivity',
        ),
    ]
