# Generated by Django 4.2.7 on 2026-04-02 11:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_rideshare_dispatch_and_payment_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='max_ride_distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum ride distance (km) the driver is willing to drive. 0 = no limit.', max_digits=6),
        ),
        migrations.AddField(
            model_name='ridesharesettings',
            name='max_passenger_search_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Maximum distance (km) from pickup to search for drivers. Prevents rural ultra-long matches.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='How far away (km) the driver will accept pickup requests from.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='minimum_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='fareconfig',
            name='per_minute_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8),
        ),
        migrations.CreateModel(
            name='FareDistanceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_km', models.DecimalField(decimal_places=2, help_text='Tier starts at this distance (km). Inclusive.', max_digits=8)),
                ('max_km', models.DecimalField(decimal_places=2, help_text='Tier ends at this distance (km). Exclusive. Use 9999 for unlimited.', max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, help_text='Per-km rate for this tier (৳).', max_digits=8)),
                ('fare_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_tiers', to='rideshare.fareconfig')),
            ],
            options={
                'ordering': ['fare_config', 'min_km'],
                'unique_together': {('fare_config', 'min_km')},
            },
        ),
    ]
