# Generated by Django 5.0 on 2026-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_ride_cash_payment_due_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='heading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='speed_kph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
