# Generated by Django 5.1.4 on 2026-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0011_searchablelocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchablelocation',
            new_name='rideshare_s_is_acti_58c511_idx',
            old_name='rideshare_s_is_acti_2b736c_idx',
        ),
    ]
