# Generated by Django 5.1.4 on 2026-04-14 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0102_balance_transaction_number"),
        ("rideshare", "0012_rename_rideshare_s_is_acti_2b736c_idx_rideshare_s_is_acti_58c511_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustomLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, default="", help_text="Optional area or landmark text shown below the custom location name.", max_length=255)),
                ("search_keywords", models.TextField(blank=True, default="", help_text="Optional comma or line-separated aliases to make searching easier.")),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("fee_paid", models.DecimalField(decimal_places=2, default=Decimal("199.00"), max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rideshare_custom_location_payments", to="base.balance")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rideshare_custom_locations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Custom Location",
                "verbose_name_plural": "User Custom Locations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usercustomlocation",
            index=models.Index(fields=["user", "is_active"], name="rideshare_u_user_id_fbde4f_idx"),
        ),
        migrations.AddIndex(
            model_name="usercustomlocation",
            index=models.Index(fields=["user", "name"], name="rideshare_u_user_id_7f4f9f_idx"),
        ),
    ]