# Generated by Django 5.1.4 on 2026-04-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0013_usercustomlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchablelocation',
            options={'ordering': ['name', 'subtitle'], 'verbose_name': 'Searchable Location', 'verbose_name_plural': 'Searchable Locations'},
        ),
        migrations.RenameIndex(
            model_name='usercustomlocation',
            new_name='rideshare_u_user_id_49dfa2_idx',
            old_name='rideshare_u_user_id_fbde4f_idx',
        ),
        migrations.RenameIndex(
            model_name='usercustomlocation',
            new_name='rideshare_u_user_id_94f37f_idx',
            old_name='rideshare_u_user_id_7f4f9f_idx',
        ),
    ]
