# Generated by Django 5.1.4 on 2026-04-14 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_user_professional_field_privacy'),
        ('rideshare', '0014_alter_searchablelocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchablelocation',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='The user who added this location (null if added by admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rideshare_added_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchablelocation',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, help_text='Payment transaction if this location was added by a user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rideshare_searchable_location_payments', to='base.balance'),
        ),
        migrations.DeleteModel(
            name='UserCustomLocation',
        ),
    ]
