# Generated by Django 5.0 on 2026-05-12 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_user_professional_field_privacy'),
        ('rideshare', '0015_remove_usercustomlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['ride', '-recorded_at'], name='rs_loc_ride_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['approval_status', 'is_online', 'is_available', '-last_seen_at'], name='rs_driver_dispatch_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['is_online', 'is_available'], name='rs_driver_online_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['-last_seen_at'], name='rs_driver_lastseen_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', 'status', '-created_at'], name='rs_ride_rider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['assigned_driver', 'status', '-created_at'], name='rs_ride_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['requested_vehicle_type', 'status'], name='rs_ride_vehicletype_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'targeted_driver', 'targeted_at'], name='rs_ride_cascade_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['payment_status'], name='rs_ride_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active', 'is_default'], name='rs_vehicle_driver_default_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active', 'vehicle_type'], name='rs_vehicle_driver_type_idx'),
        ),
    ]
