# Generated by Django 5.1.4 on 2026-07-29 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_perf_indexes_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rideshare.driverprofile')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='rideshare.ride')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='rs_rating_driver_idx')],
            },
        ),
    ]
