# Generated by Django 5.0 on 2026-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable id the app references, e.g. bn_feed_native.', max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('network', models.CharField(choices=[('applovin_max', 'AppLovin MAX (mediation)')], default='applovin_max', max_length=30)),
                ('ad_format', models.CharField(choices=[('native', 'Native'), ('mrec', 'MREC (300x250)'), ('banner', 'Adaptive Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded'), ('app_open', 'App Open')], default='native', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('ad_unit_id_android', models.CharField(blank=True, default='', max_length=120)),
                ('ad_unit_id_ios', models.CharField(blank=True, default='', max_length=120)),
                ('frequency', models.PositiveIntegerField(default=4, help_text='Feed/list: show an ad after every N items.')),
                ('min_app_version', models.CharField(blank=True, default='', help_text='Optional — only serve on app builds >= this (e.g. 8.0.51).', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch — turn ALL ads off instantly.')),
                ('applovin_sdk_key', models.TextField(blank=True, default='', help_text='AppLovin MAX SDK key (from the MAX dashboard).')),
                ('test_mode', models.BooleanField(default=True, help_text='Show MAX test ads (use while integrating; turn off for real ads).')),
                ('max_ad_content_rating', models.CharField(choices=[('G', 'G — General (no gambling / alcohol / sexual)'), ('PG', 'PG — Parental guidance'), ('T', 'T — Teen'), ('MA', 'MA — Mature')], default='G', help_text='Max ad content rating. Keep G to block gambling & nudity.', max_length=2)),
                ('blocked_keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords to also discourage (advisory; main blocking is the rating + network block-lists).')),
            ],
            options={
                'verbose_name': 'Ad Settings',
                'verbose_name_plural': 'Ad Settings',
            },
        ),
    ]
