# Generated by Django 5.1.4 on 2026-01-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0002_add_is_edited_fields'),
        ('base', '0104_ailink_openai_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChatSession',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_chat_session', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='adsyconnect.chatroom')),
            ],
            options={
                'db_table': 'adsyconnect_active_chat_session',
            },
        ),
    ]
