# Generated by Django 5.1.4 on 2026-04-12 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0003_activechatsession'),
        ('base', '0104_ailink_openai_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=80, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('busy', 'Busy'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('missed', 'Missed'), ('failed', 'Failed')], default='ringing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsyconnect_incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsyconnect_outgoing_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adsyconnect_call_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', '-started_at'], name='adsyconnect_caller_started_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['callee', '-started_at'], name='adsyconnect_callee_started_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', '-started_at'], name='adsyconnect_status_started_idx'),
        ),
    ]