# Generated by Django 5.0 on 2026-04-11 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0004_callsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callsession',
            new_name='adsyconnect_caller__573439_idx',
            old_name='adsyconnect_caller_started_idx',
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='adsyconnect_callee__ee0fbd_idx',
            old_name='adsyconnect_callee_started_idx',
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='adsyconnect_status_18df3f_idx',
            old_name='adsyconnect_status_started_idx',
        ),
        migrations.AlterField(
            model_name='callsession',
            name='last_status_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
