# Generated by Django 5.0 on 2026-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0005_rename_adsyconnect_caller_started_idx_adsyconnect_caller__573439_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='cleared_at_user1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cleared_at_user2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
