# Generated by Django 5.0 on 2026-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0006_chatroom_cleared_at_user1_chatroom_cleared_at_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='archived_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='archived_by_user2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='muted_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='muted_by_user2',
            field=models.BooleanField(default=False),
        ),
    ]
