# Generated by Django 5.1.4 on 2026-07-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0011_groupmessage_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='adsyconnect.groupmessage'),
        ),
    ]
