# Generated by Django 5.0 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0012_groupmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroupmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
