# Generated by Django 5.0 on 2026-07-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0013_chatgroupmembership_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activechatsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='adsyconnect.chatgroup'),
        ),
    ]
