# Generated by Django 5.1.4 on 2026-08-09 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0016_groupmessage_edited_at_groupmessage_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('left', 'Left')], default='ringing', max_length=20)),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adsyconnect_call_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='adsyconnect.callsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsyconnect_call_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adsyconnect_call_participants',
                'ordering': ['invited_at'],
                'indexes': [models.Index(fields=['user', '-invited_at'], name='adsyconnect_user_id_5ad1c3_idx'), models.Index(fields=['session', 'status'], name='adsyconnect_session_04f588_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
