# Generated by Django 5.0 on 2026-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsyconnect', '0019_chatgroup_created_from_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinestatus',
            name='connection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
