# Generated by Django 5.0 on 2026-06-07 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0117_user_is_suspended_user_suspended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='engagement_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('active_days_7d', models.PositiveIntegerField(default=0)),
                ('active_days_30d', models.PositiveIntegerField(default=0)),
                ('events_7d', models.PositiveIntegerField(default=0)),
                ('events_30d', models.PositiveIntegerField(default=0)),
                ('active_days_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('lifecycle_stage', models.CharField(choices=[('new', 'New'), ('onboarding', 'Onboarding'), ('activated', 'Activated'), ('habitual', 'Habitual'), ('at_risk', 'At risk'), ('dormant', 'Dormant'), ('resurrected', 'Resurrected'), ('churned', 'Churned')], default='new', max_length=20)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('value_tier', models.CharField(default='explorer', max_length=20)),
                ('top_interests', models.JSONField(blank=True, default=list)),
                ('top_surfaces', models.JSONField(blank=True, default=dict)),
                ('preferred_hours', models.JSONField(blank=True, default=list)),
                ('pending', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lifecycle_stage'], name='eng_state_stage_idx'), models.Index(fields=['-last_active_at'], name='eng_state_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('surface', models.CharField(blank=True, default='', max_length=32)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='eng_event_user_recent_idx'), models.Index(fields=['event_type', '-created_at'], name='eng_event_type_recent_idx')],
            },
        ),
    ]
