# Generated by Django 5.0 on 2026-06-07 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NudgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_key', models.CharField(max_length=64)),
                ('channel', models.CharField(default='push', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('deep_link', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-sent_at'], name='eng_nudge_user_recent_idx'), models.Index(fields=['user', 'nudge_key', '-sent_at'], name='eng_nudge_key_idx')],
            },
        ),
    ]
