# Generated by Django 5.1.4 on 2025-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_add_ticket_read_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
