# Generated by Django 5.1.4 on 2025-05-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_last_read_at'),
    ]

    operations = [
    ]
