# Generated by Django 5.1.4 on 2025-05-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20250530_1307'),
    ]

    operations = [
    ]
