# Generated by Django 5.1.4 on 2025-05-30 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20250530_1316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Rich text content with HTML formatting')),
                ('target_type', models.CharField(choices=[('selected', 'Selected Users'), ('all', 'All Users'), ('staff', 'Staff Members Only'), ('non_staff', 'Non-Staff Members Only')], default='selected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tickets_created_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bulk_tickets', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text="Specific users to send tickets to (only used when target_type is 'selected')", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Ticket',
                'verbose_name_plural': 'Bulk Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
