# Generated by Django 5.0.1 on 2025-12-01 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Year 2025 Referral Reward', max_length=100)),
                ('referrer_reward', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('referee_reward', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='referral_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('referrer', 'Referrer'), ('referee', 'Referee')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('claimed', 'Claimed')], default='pending', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('has_posted_bn', models.BooleanField(default=False)),
                ('has_completed_microgig', models.BooleanField(default=False)),
                ('has_kyc_verified', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='referral_rewards.referralrewardprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('program', 'user', 'claim_type', 'referred_user')},
            },
        ),
    ]
