# Generated by Django 5.1.4 on 2025-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
