# Generated by Django 5.0 on 2026-07-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, help_text="Store owner's reply to this review", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_response_at',
            field=models.DateTimeField(blank=True, help_text='When the store owner replied', null=True),
        ),
    ]
