# Generated by Django 5.1.4 on 2025-03-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='mobile_recharge.operator'),
        ),
    ]
