# Generated by Django 5.1.4 on 2025-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0002_recharge_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('balance', 'Balance'), ('data', 'Data'), ('voice', 'Voice'), ('combo', 'Combo')], max_length=20),
        ),
    ]
