# Generated by Django 5.1.4 on 2025-03-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0003_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
