# Generated by Django 5.0 on 2026-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_recharge', '0004_alter_recharge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Recharge Provider', max_length=100)),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn ON only after the API details below are filled in. While OFF, recharges stay pending for manual processing.')),
                ('base_url', models.URLField(blank=True, default='', help_text='Provider API base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Any extra provider parameters (sender id, account, etc.) as JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recharge provider (API)',
                'verbose_name_plural': 'Recharge provider (API)',
            },
        ),
        migrations.AlterModelOptions(
            name='recharge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recharge',
            name='balance_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recharge',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recharge',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='provider_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recharge',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
