# Generated by Django 5.1.4 on 2024-12-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_referbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='referbonus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
