# Generated by Django 5.1.4 on 2024-12-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classifiedcategorypostmedia_classifiedcategorypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_categories_post', to='base.classifiedcategory'),
        ),
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_categories_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
