# Generated by Django 5.1.4 on 2024-12-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_referbonus_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
