# Generated by Django 5.1.4 on 2024-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_adminnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigposttask',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
