# Generated by Django 5.1.4 on 2024-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_microgigposttask_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='active_gigs',
            field=models.BooleanField(default=True),
        ),
    ]
