# Generated by Django 5.1.4 on 2024-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
    ]
