# Generated by Django 5.1.4 on 2024-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_nid_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referral_code',
            new_name='refer_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
