# Generated by Django 5.1.4 on 2024-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_referral_code_user_refer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
