# Generated by Django 5.1.4 on 2024-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_microgigposttask_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microgigposttask',
            name='status',
        ),
        migrations.AddField(
            model_name='microgigposttask',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microgigposttask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microgigposttask',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='microgigposttask',
            name='medias',
            field=models.ManyToManyField(blank=True, null=True, to='base.microgigpostmedia'),
        ),
    ]
