# Generated by Django 5.1.4 on 2024-12-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_refer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='refer_code',
            new_name='referral_code',
        ),
    ]
