# Generated by Django 5.1.4 on 2024-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_refer_code_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
