# Generated by Django 5.1.4 on 2024-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_about_user_face_link_user_gmail_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_link',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail_link',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
