# Generated by Django 5.1.4 on 2024-12-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_nid_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nid',
            name='image',
        ),
    ]
