# Generated by Django 5.1.4 on 2024-12-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='label',
        ),
    ]
