# Generated by Django 5.1.4 on 2024-12-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotice',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
