# Generated by Django 5.1.4 on 2024-12-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_answer_faq_content_rename_question_faq_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refer',
        ),
        migrations.AddField(
            model_name='user',
            name='refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
