# Generated by Django 5.1.4 on 2024-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_adminnotice_options_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='target_city',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='microgigpost',
            name='target_state',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.RemoveField(
            model_name='microgigpost',
            name='target_country',
        ),
        migrations.AddField(
            model_name='microgigpost',
            name='target_country',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
