# Generated by Django 5.1.4 on 2024-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_microgigpost_target_city_microgigpost_target_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microgigpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='microgigpost',
            name='target_city',
        ),
        migrations.RemoveField(
            model_name='microgigpost',
            name='target_state',
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='target_country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
