# Generated by Django 5.1.4 on 2024-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_microgigpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedcategorypost',
            name='image',
        ),
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='city',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='country',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='state',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
