# Generated by Django 5.1.4 on 2024-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_nid_other_document_nid_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='nid',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
