# Generated by Django 5.1.4 on 2025-01-01 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_nid_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
