# Generated by Django 5.1.4 on 2024-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_classifiedcategorypost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='method',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending'),
        ),
    ]
