# Generated by Django 5.1.4 on 2025-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_balance_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='service_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
