# Generated by Django 5.1.1 on 2024-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_balance_method_balance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='nid',
        ),
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.ManyToManyField(blank=True, null=True, to='base.nid'),
        ),
    ]
