# Generated by Django 5.1.4 on 2025-01-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_division_district_policestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='district',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='PoliceStation',
        ),
    ]
