# Generated by Django 5.1.4 on 2024-12-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_microgigposttask_submit_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='method',
            new_name='type',
        ),
    ]
