# Generated by Django 5.1.4 on 2025-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='upazila',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
