# Generated by Django 5.1.4 on 2024-12-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_classifiedcategorypost_git_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedcategorypost',
            old_name='git_status',
            new_name='gig_status',
        ),
        migrations.RenameField(
            model_name='microgigpost',
            old_name='git_status',
            new_name='gig_status',
        ),
    ]
