# Generated by Django 5.1.4 on 2025-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_classifiedcategorypost_upazila'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigposttask',
            name='task_completion_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
