# Generated by Django 5.1.4 on 2025-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_microgigposttask_task_completion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='action_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
