# Generated by Django 5.1.4 on 2024-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_git_status_classifiedcategorypost_gig_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
