# Generated by Django 5.1.4 on 2024-12-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_classifiedcategorypost_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc',
            field=models.BooleanField(default=False),
        ),
    ]
