# Generated by Django 5.1.4 on 2025-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_microgigpost_action_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='card_number',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
