# Generated by Django 5.1.4 on 2025-03-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_microgigposttask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referbonus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comission_bonus', to=settings.AUTH_USER_MODEL),
        ),
    ]
