# Generated by Django 5.1.4 on 2024-12-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_transaction_type_balance_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='payment_confirmed_at',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
