# Generated by Django 5.1.4 on 2025-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_referbonus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microgigpost',
            name='medias',
            field=models.ManyToManyField(blank=True, null=True, related_name='micro_gig_posts', to='base.microgigpostmedia'),
        ),
    ]
