# Generated by Django 5.1.4 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_microgigpost_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
