# Generated by Django 5.1.4 on 2025-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_classifiedcategory_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='title_eng',
            field=models.CharField(default='shop', max_length=256),
        ),
    ]
