# Generated by Django 5.1.4 on 2024-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_balance_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-updated_at']},
        ),
    ]
