# Generated by Django 5.1.4 on 2024-12-23 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_balance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
