# Generated by Django 5.1.4 on 2025-03-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_classifiedcategory_title_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedcategory',
            old_name='title_eng',
            new_name='business_type',
        ),
    ]
