# Generated by Django 5.1.4 on 2024-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_user_refer'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balance',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
    ]
