# Generated by Django 5.1.4 on 2025-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_productcategory_productmedia_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='base.productmedia'),
        ),
    ]
