# Generated by Django 5.1.4 on 2024-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_balance_approved_balance_completed_balance_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
