# Generated by Django 5.1.4 on 2024-12-25 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='bank_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classifiedcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_categories_post', to='base.classifiedcategory'),
        ),
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_categories_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='microgigcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_gig_posts', to='base.microgigcategory'),
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_gig_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='microgigposttask',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.microgigpost'),
        ),
        migrations.AlterField(
            model_name='microgigposttask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_gig_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
