# Generated by Django 5.1.4 on 2024-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_balance_bank_status_alter_balance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='active_service',
            field=models.BooleanField(default=True),
        ),
    ]
