# Generated by Django 5.1.4 on 2024-12-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_classifiedcategorypost_active_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedcategorypost',
            old_name='gig_status',
            new_name='service_status',
        ),
    ]
