# Generated by Django 5.1.4 on 2025-03-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_fee',
            new_name='delivery_fee_free',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_fee_inside_dhaka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_fee_outside_dhaka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
