# Generated by Django 5.1.4 on 2024-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_gig_status_classifiedcategorypost_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='complete_gig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microgigpost',
            name='stop_gig',
            field=models.BooleanField(default=False),
        ),
    ]
