# Generated by Django 5.1.4 on 2025-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_delivery_fee_product_delivery_fee_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='store_username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
