# Generated by Django 5.1.4 on 2024-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_microgigpost_complete_gig_microgigpost_stop_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microgigpost',
            name='gig_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
