# Generated by Django 5.1.4 on 2025-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_user_store_address_user_store_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
