# Generated by Django 5.1.4 on 2025-03-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_product_regular_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
