# Generated by Django 5.1.4 on 2024-12-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_microgigpost_gig_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microgigpost',
            name='complete_gig',
        ),
    ]
