# Generated by Django 5.1.4 on 2024-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_microgigpost_complete_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
