# Generated by Django 5.1.4 on 2024-12-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_microgigpost_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nid',
        ),
        migrations.AddField(
            model_name='nid',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nid',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nid',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nid',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nid',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_pending',
            field=models.BooleanField(default=False),
        ),
    ]
