# Generated by Django 5.1.4 on 2025-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
