# Generated by Django 5.1.4 on 2024-12-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_classifiedcategory_user_remove_user_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nid', to=settings.AUTH_USER_MODEL),
        ),
    ]
