# Generated by Django 5.1.4 on 2024-12-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_classifiedcategory_user_alter_nid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer_count',
            field=models.IntegerField(default=0),
        ),
    ]
