# Generated by Django 5.1.4 on 2024-12-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_user_refer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microgigposttask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_gig_worker', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
