# Generated by Django 5.1.4 on 2025-04-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_productbenefit_productfaq_producttrustbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_advanced',
            field=models.BooleanField(default=False),
        ),
    ]
