# Generated by Django 5.1.4 on 2024-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_microgigposttask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='merchant_invoice_no',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='shurjopay_order_id',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
