# Generated by Django 5.1.4 on 2025-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_product_is_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='classifiedcategorypost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='microgigcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='microgigpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttrustbadge',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
