# Generated by Django 5.1.4 on 2025-04-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_classifiedcategory_slug_classifiedcategorypost_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0000000000', editable=False, max_length=10, unique=True),
        ),
    ]
