# Generated by Django 5.1.4 on 2025-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
