# Generated by Django 5.1.4 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_username',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
