# Generated by Django 5.1.4 on 2025-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_user_store_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
