# Generated by Django 5.1.4 on 2025-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_user_business_name_user_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='business_name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
