# Generated by Django 5.1.4 on 2025-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_rename_business_name_user_company_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
