# Generated by Django 5.1.4 on 2025-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_topcontributor',
            field=models.BooleanField(default=False),
        ),
    ]
