# Generated by Django 5.1.4 on 2025-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_user_is_topcontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='upazila',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
