# Generated by Django 5.1.4 on 2025-05-06 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_user_country_user_upazila'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diamond_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiamondTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('gift', 'Gift'), ('bonus', 'Bonus'), ('refund', 'Refund'), ('admin', 'Admin Adjustment')], max_length=20)),
                ('amount', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('completed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_diamonds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
