# Generated by Django 5.1.4 on 2025-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_diamondpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
