# Generated by Django 5.1.4 on 2025-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_productcategory_icon_productcategory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='icon',
            new_name='badge',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='badge_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='hot_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
