# Generated by Django 5.1.4 on 2025-05-11 11:07

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forsalecategory',
            name='id',
            field=models.BigIntegerField(default=base.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
