# Generated by Django 5.1.4 on 2025-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_forsalecategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedcategorypost',
            name='medias',
            field=models.ManyToManyField(blank=True, to='base.classifiedcategorypostmedia'),
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='micro_gig_posts', to='base.microgigpostmedia'),
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='target_device',
            field=models.ManyToManyField(blank=True, to='base.targetdevice'),
        ),
        migrations.AlterField(
            model_name='microgigpost',
            name='target_network',
            field=models.ManyToManyField(blank=True, to='base.targetnetwork'),
        ),
        migrations.AlterField(
            model_name='microgigposttask',
            name='medias',
            field=models.ManyToManyField(blank=True, to='base.microgigpostmedia'),
        ),
    ]
