# Generated by Django 5.1.4 on 2025-05-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_classifiedcategorypost_medias_and_more'),
        ('sale', '0004_forsalebanner_forsalecategory_alter_salepostimage_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForSaleBanner',
        ),
        migrations.DeleteModel(
            name='ForSaleCategory',
        ),
    ]
