# Generated by Django 5.1.4 on 2025-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_delete_forsalebanner_delete_forsalecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_username',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
