# Generated by Django 5.1.4 on 2025-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_user_store_name_alter_user_store_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_commerce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_humanities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_science',
            field=models.BooleanField(default=False),
        ),
    ]
