# Generated by Django 5.1.4 on 2025-05-27 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_product_is_commerce_product_is_humanities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referbonus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referral Commission', 'verbose_name_plural': 'Referral Commissions'},
        ),
        migrations.AddField(
            model_name='referbonus',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='referbonus',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='referbonus',
            name='commission_type',
            field=models.CharField(choices=[('gig_completion', 'Gig Completion'), ('pro_subscription', 'Pro Subscription'), ('gold_sponsor', 'Gold Sponsor')], default='gig_completion', max_length=20),
        ),
        migrations.AddField(
            model_name='referbonus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referbonus',
            name='referred_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referbonus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_bonus', to=settings.AUTH_USER_MODEL),
        ),
    ]
