# Generated by Django 5.1.4 on 2025-05-29 07:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_alter_referbonus_options_referbonus_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
