# Generated by Django 5.1.4 on 2025-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_eshopbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='Version name (e.g., 1.0.0)', max_length=50)),
                ('version_code', models.PositiveIntegerField(help_text='Version code (integer, e.g., 100)')),
                ('download_url', models.URLField(help_text='URL to download the APK', max_length=500)),
                ('release_notes', models.TextField(blank=True, help_text="What's new in this version")),
                ('is_active', models.BooleanField(default=True, help_text='Is this the currently active version')),
                ('min_android_version', models.CharField(default='5.0', help_text='Minimum Android version required', max_length=20)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, help_text='APK file size in MB', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Android App Version',
                'verbose_name_plural': 'Android App Versions',
                'ordering': ['-version_code'],
            },
        ),
    ]
