# Generated by Django 5.1.4 on 2025-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_androidappversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_limit',
            field=models.IntegerField(default=10),
        ),
    ]
