# Generated by Django 5.1.4 on 2025-05-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_productslotpackage'),
        ('base', '0081_add_product_limit_to_user'),
    ]

    operations = [
    ]
