# Generated by Django 5.1.4 on 2025-05-31 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_merge_20250530_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
            ],
        ),
    ]
