# Generated by Django 5.1.4 on 2025-06-09 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_ailink'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for financial notifications', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adminnotice',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminnotice',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notice'), ('order_received', 'New Order Received'), ('withdraw_successful', 'Withdraw Successful'), ('mobile_recharge_successful', 'Mobile Recharge Successful'), ('pro_subscribed', 'Pro Subscription Activated'), ('pro_expiring', 'Pro Subscription Expiring'), ('gig_posted', 'Gig Posted Successfully'), ('general', 'General Update')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='adminnotice',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Reference ID (order ID, transaction ID, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminnotice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global notices, specify user for personalized notifications', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
