# Generated by Django 5.1.4 on 2025-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_adminnotice_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microgigpost',
            name='action_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
