# Generated by Django 5.1.4 on 2025-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_alter_adminnotice_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords to help with search functionality', null=True),
        ),
    ]
