# Generated by Django 5.1.4 on 2025-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_classifiedcategory_search_keywords'),
        ('elearning', '0005_remove_elearningsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batches',
            field=models.ManyToManyField(blank=True, help_text='Select batches where this product should be displayed', related_name='products', to='elearning.batch'),
        ),
    ]
