# Generated by Django 5.1.4 on 2025-06-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_product_batches'),
        ('elearning', '0005_remove_elearningsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='divisions',
            field=models.ManyToManyField(blank=True, help_text='Select divisions where this product should be displayed', related_name='products', to='elearning.division'),
        ),
    ]
