# Generated by Django 5.1.4 on 2025-07-02 08:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_alter_adminnotice_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='eshopbanner',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='eshopbanner',
            name='device_type',
            field=models.CharField(choices=[('all', 'All Devices'), ('mobile', 'Mobile Only'), ('desktop', 'Desktop Only')], default='all', help_text='Target device type for this banner', max_length=10),
        ),
        migrations.AddField(
            model_name='eshopbanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this banner should be displayed'),
        ),
        migrations.AddField(
            model_name='eshopbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optimized image for mobile devices', null=True, upload_to='eshop_banner/mobile/'),
        ),
        migrations.AddField(
            model_name='eshopbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)'),
        ),
    ]
