# Generated by Django 5.1.4 on 2025-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_store_alter_eshopbanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EshopLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
