# Generated by Django 5.1.4 on 2025-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_eshoplogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords to help customers find your product', null=True),
        ),
    ]
