# Generated by Django 5.1.4 on 2025-07-26 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_product_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
