# Generated by Django 5.1.4 on 2025-07-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_countryversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryversion',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
