# Generated by Django 5.1.4 on 2025-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_alter_countryversion_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='microgigpost',
            name='appeal_count',
            field=models.IntegerField(default=0, help_text='Number of times this gig has been appealed'),
        ),
        migrations.AddField(
            model_name='microgigpost',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
    ]
