# Generated by Django 5.1.4 on 2025-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='transaction_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
