# Generated by Django 5.0.1 on 2025-12-05 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_fcmtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ailink',
            options={'verbose_name': 'AI Link', 'verbose_name_plural': 'AI Links'},
        ),
        migrations.AddField(
            model_name='ailink',
            name='api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key (starts with sk-)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ailink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ailink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this AI configuration is active'),
        ),
        migrations.AddField(
            model_name='ailink',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', help_text='OpenAI model to use (e.g., gpt-3.5-turbo, gpt-4)', max_length=50),
        ),
        migrations.AddField(
            model_name='ailink',
            name='name',
            field=models.CharField(default='AdsyAI', help_text='Name for this AI configuration', max_length=100),
        ),
        migrations.AddField(
            model_name='ailink',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('cloudflare', 'Cloudflare Worker')], default='openai', help_text='AI provider to use', max_length=20),
        ),
        migrations.AddField(
            model_name='ailink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ailink',
            name='link',
            field=models.URLField(blank=True, help_text='Cloudflare worker URL (only for cloudflare provider)', null=True),
        ),
    ]
