# Generated by Django 5.1.4 on 2026-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_ailink_openai_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='is_food_zone',
            field=models.BooleanField(default=False, help_text='Check this to include posts from this category in Food Zone section'),
        ),
    ]
