# Generated by Django 5.1.4 on 2026-06-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_banner_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('deep_link', models.CharField(blank=True, default='', help_text='In-app path to open, e.g. "/business-network/posts/123" or "/eshop". Leave blank for no "Visit" button.', max_length=500)),
                ('notification_type', models.CharField(blank=True, default='general', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Recipient. Null = broadcast/announcement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'user_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_ea6762_idx'), models.Index(fields=['-created_at'], name='user_notifi_created_dc576f_idx')],
            },
        ),
    ]
