# Generated by Django 5.1.4 on 2026-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_user_is_suspended_user_suspended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
