# Generated by Django 5.0 on 2026-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0118_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplatePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates (preview)',
            },
        ),
    ]
