# Generated by Django 5.0 on 2026-06-08 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_emailtemplatepreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_price', models.DecimalField(decimal_places=2, default=Decimal('299'), help_text='Normal monthly price (shown struck-through during a discount).', max_digits=8)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('149'), help_text='Discounted monthly price charged while the discount is active.', max_digits=8)),
                ('discount_active', models.BooleanField(default=True)),
                ('discount_label', models.CharField(blank=True, default='Limited-time offer', max_length=120)),
                ('yearly_discount', models.DecimalField(decimal_places=2, default=Decimal('289'), help_text='Flat amount saved when buying 12 months at once.', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pro pricing',
                'verbose_name_plural': 'Pro pricing',
            },
        ),
    ]
