# Generated by Django 5.0 on 2026-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0121_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
