# Generated by Django 5.0 on 2026-06-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_user_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_search_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_search_city',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='last_search_state',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='last_search_upazila',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
