# Generated by Django 5.0 on 2026-06-10 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0123_user_last_search_at_user_last_search_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='last_promo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='promo_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active', 'last_promo_at'], name='fcm_guest_promo_idx'),
        ),
    ]
