# Generated by Django 5.0 on 2026-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_fcmtoken_last_promo_at_fcmtoken_promo_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Who this is, e.g. "Manager", "Assistant Manager"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Email Recipient',
                'verbose_name_plural': 'Admin Email Recipients',
                'ordering': ['email'],
            },
        ),
    ]
