# Generated by Django 5.0 on 2026-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0125_adminemailrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotice',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System Notice'), ('order_received', 'New Order Received'), ('withdraw_successful', 'Withdraw Successful'), ('mobile_recharge_successful', 'Mobile Recharge Successful'), ('transfer_sent', 'Money Transfer Sent'), ('transfer_received', 'Money Transfer Received'), ('deposit_successful', 'Deposit Successful'), ('pro_subscribed', 'Pro Subscription Activated'), ('pro_expiring', 'Pro Subscription Expiring'), ('gig_posted', 'Gig Posted Successfully'), ('gig_approved', 'Gig Approved by Admin'), ('gig_rejected', 'Gig Rejected by Admin'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('service_approved', 'Amar Sheba Approved'), ('sale_approved', 'Sale Ad Approved'), ('sponsor_approved', 'Gold Sponsor Approved'), ('general', 'General Update')], default='general', max_length=30),
        ),
    ]
