# Generated by Django 5.0 on 2026-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0126_alter_adminnotice_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed (user choice)'), ('bounced', 'Bounced / undeliverable'), ('invalid', 'Invalid address'), ('complaint', 'Spam complaint')], default='unsubscribed', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions (unsub / bounced)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='base_emails_email_96b577_idx')],
            },
        ),
    ]
