# Generated by Django 5.0 on 2026-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0127_emailsuppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ceo_welcome_sent',
            field=models.BooleanField(default=False),
        ),
    ]
