# Generated by Django 5.0 on 2026-06-13 07:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0128_user_ceo_welcome_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmail',
            fields=[
            ],
            options={
                'verbose_name': 'Valid / active email',
                'verbose_name_plural': 'Valid / active emails (deliverable)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='emailsuppression',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Suppression', 'verbose_name_plural': 'Email Suppressions (invalid / unsubscribed)'},
        ),
    ]
