# Generated by Django 5.1.4 on 2026-07-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0130_popularsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, default='', help_text='e.g. "BBA — Dhaka University"', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='education_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Comma-separated, e.g. "বাংলা, English"', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, default='', help_text='Comma-separated, e.g. "Graphic Design, Marketing"', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_public',
            field=models.BooleanField(default=True),
        ),
    ]
