# Generated by Django 5.0 on 2026-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0132_user_otp_created_at_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='who_can_message',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People who follow me'), ('following', 'People I follow'), ('mutual', 'Mutual connections only')], default='everyone', max_length=20),
        ),
    ]
