# Generated by Django 5.0 on 2026-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0134_user_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Greeting',
                'ordering': ['order', 'id'],
            },
        ),
    ]
