# Generated by Django 5.0 on 2026-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0135_homegreeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProTrialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Turn the free Pro trial offer on or off everywhere.')),
                ('days', models.PositiveIntegerField(default=15, help_text='How many days of Pro a trial grants.')),
                ('require_kyc', models.BooleanField(default=True, help_text='Only KYC-verified accounts may claim the trial.')),
            ],
            options={
                'verbose_name': 'Pro Trial Config',
                'verbose_name_plural': 'Pro Trial Config',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pro_trial_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
