# Generated by Django 5.1.4 on 2026-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0136_protrialconfig_user_pro_trial_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_list_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People who follow me'), ('only_me', 'Only me')], default='everyone', max_length=20),
        ),
    ]
