# Generated by Django 5.0 on 2026-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0137_user_follow_list_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='who_can_call',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People who follow me'), ('following', 'People I follow'), ('mutual', 'Mutual connections only'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow_list_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'People who follow me'), ('following', 'People I follow'), ('only_me', 'Only me')], default='everyone', max_length=20),
        ),
    ]
