# Generated by Django 5.0.1 on 2025-11-30 09:51

import django.db.models.deletion
import uuid
import workspace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('design', 'Design & Creative'), ('development', 'Programming & Tech'), ('writing', 'Writing & Translation'), ('marketing', 'Digital Marketing'), ('business', 'Business & Consulting')], default='design', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=workspace.models.gig_image_path)),
                ('delivery_time', models.PositiveIntegerField(default=3, help_text='Delivery time in days')),
                ('revisions', models.PositiveIntegerField(default=2, help_text='Number of revisions included')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig',
                'verbose_name_plural': 'Gigs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('revision', 'Revision Requested')], default='pending', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workspace.gig')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_orders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Order',
                'verbose_name_plural': 'Gig Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='workspace.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_favorite_gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Favorite',
                'verbose_name_plural': 'Gig Favorites',
                'unique_together': {('gig', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GigReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workspace.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_gig_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Review',
                'verbose_name_plural': 'Gig Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('gig', 'user')},
            },
        ),
    ]
