# Generated by Django 5.0.1 on 2025-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills/expertise tags'),
        ),
    ]
