# Generated by Django 5.0.1 on 2025-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='order_messages/'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
