# Generated by Django 5.0.1 on 2025-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_ordermessage_file_name_ordermessage_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='order_messages/'),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=20),
        ),
    ]
