# Generated by Django 5.0.1 on 2025-11-30 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_ordermessage_file_size_alter_ordermessage_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., i-heroicons-paint-brush)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gig Category',
                'verbose_name_plural': 'Gig Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GigDeliveryTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Display label (e.g., '1 Day', '3 Days')", max_length=50)),
                ('days', models.PositiveIntegerField(help_text='Number of days')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Delivery Time Option',
                'verbose_name_plural': 'Delivery Time Options',
                'ordering': ['order', 'days'],
            },
        ),
        migrations.CreateModel(
            name='GigRevisionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Display label (e.g., '1 Revision', 'Unlimited')", max_length=50)),
                ('count', models.PositiveIntegerField(help_text='Number of revisions (use 999 for unlimited)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Revision Option',
                'verbose_name_plural': 'Revision Options',
                'ordering': ['order', 'count'],
            },
        ),
        migrations.CreateModel(
            name='GigSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='workspace.gigcategory')),
            ],
            options={
                'verbose_name': 'Gig Skill',
                'verbose_name_plural': 'Gig Skills',
                'ordering': ['name'],
            },
        ),
    ]
