# Generated by Django 5.0.1 on 2025-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_gigcategory_gigdeliverytime_gigrevisionoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of what buyers will get'),
        ),
    ]
