# Generated by Django 5.0.1 on 2025-11-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_alter_ordermessage_sender_gigordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs'),
        ),
    ]
