# Generated by Django 5.0.1 on 2025-11-30 20:35

import uuid
import workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_gig_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Banner title (for admin reference)', max_length=100)),
                ('image', models.ImageField(upload_to=workspace.models.workspace_banner_path)),
                ('link', models.URLField(blank=True, help_text='URL to navigate when banner is clicked', null=True)),
                ('link_type', models.CharField(choices=[('external', 'External URL'), ('internal', 'Internal Page'), ('gig', 'Gig Detail'), ('category', 'Category Filter')], default='external', max_length=20)),
                ('internal_path', models.CharField(blank=True, help_text='Internal path (e.g., /business-network/workspaces?category=design)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing the banner', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing the banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace Banner',
                'verbose_name_plural': 'Workspace Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
