# Generated by Django 5.0.1 on 2025-12-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_workspacebanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_service_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage fee charged to buyer on order amount (e.g., 5 for 5%)', max_digits=5)),
                ('buyer_service_fee_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum service fee in BDT', max_digits=10)),
                ('buyer_service_fee_max', models.DecimalField(decimal_places=2, default=500, help_text='Maximum service fee cap in BDT', max_digits=10)),
                ('buyer_processing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed processing fee in BDT', max_digits=10)),
                ('buyer_fee_waived', models.BooleanField(default=True, help_text='If checked, buyer service fees are waived (promotional period)')),
                ('seller_commission_percent', models.DecimalField(decimal_places=2, default=10, help_text='Platform commission percentage deducted from seller earnings (e.g., 10 for 10%)', max_digits=5)),
                ('seller_commission_min', models.DecimalField(decimal_places=2, default=5, help_text='Minimum commission in BDT', max_digits=10)),
                ('seller_commission_max', models.DecimalField(decimal_places=2, default=5000, help_text='Maximum commission cap in BDT', max_digits=10)),
                ('seller_withdrawal_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee for withdrawing earnings in BDT', max_digits=10)),
                ('seller_fee_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Promotional discount on seller commission (e.g., 20 for 20% off)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Fee Settings',
                'verbose_name_plural': 'Gig Fee Settings',
            },
        ),
    ]
