# Generated by Django 5.0.1 on 2025-12-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_add_gig_fee_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='workspace.gigorder'),
        ),
    ]
