# Generated by Django 5.0.1 on 2025-12-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_add_order_to_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the gig was reviewed by admin', null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
