# Generated by Django 5.0.1 on 2025-12-01 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_add_gig_approval_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('revision', 'Revision Requested'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('unresponsive_seller', 'Seller is unresponsive'), ('unresponsive_buyer', 'Buyer is unresponsive'), ('work_not_delivered', 'Work not delivered'), ('work_not_as_described', 'Work not as described'), ('quality_issues', 'Quality issues'), ('late_delivery', 'Late delivery'), ('payment_issue', 'Payment issue'), ('communication_issue', 'Communication breakdown'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('evidence', models.JSONField(blank=True, default=list, help_text='List of evidence URLs/attachments')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_buyer', 'Resolved - Buyer Wins'), ('resolved_seller', 'Resolved - Seller Wins'), ('resolved_partial', 'Resolved - Partial Refund'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Resolution explanation visible to both parties', null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund if partial refund', max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='workspace.gigorder')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Dispute',
                'verbose_name_plural': 'Order Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
