# Generated by Django 5.0.1 on 2025-12-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_add_order_dispute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gigfeesettings',
            options={'verbose_name': 'Platform Fee Settings', 'verbose_name_plural': 'Platform Fee Settings'},
        ),
        migrations.AddField(
            model_name='gigfeesettings',
            name='buyer_fee_percent',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Fee charged to buyer when placing order (e.g., 2.5 means 2.5%)', max_digits=5, verbose_name='Buyer Fee %'),
        ),
        migrations.AddField(
            model_name='gigfeesettings',
            name='fees_enabled',
            field=models.BooleanField(default=True, help_text='Uncheck to disable all fees (promotional period)', verbose_name='Fees Enabled'),
        ),
        migrations.AddField(
            model_name='gigfeesettings',
            name='seller_fee_percent',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Fee deducted from seller when order completes (e.g., 2.5 means 2.5%)', max_digits=5, verbose_name='Seller Fee %'),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='buyer_fee_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='buyer_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='buyer_service_fee_max',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='buyer_service_fee_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='buyer_service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='seller_commission_max',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='seller_commission_min',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='seller_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='seller_fee_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gigfeesettings',
            name='seller_withdrawal_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
