# Generated by Django 5.0.1 on 2025-12-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_simplified_fee_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceReport',
            fields=[
            ],
            options={
                'verbose_name': '📊 Earnings Report',
                'verbose_name_plural': '📊 Earnings Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workspace.gigorder',),
        ),
    ]
