# Generated by Django 5.1.4 on 2025-05-10 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('brand-new', 'Brand New'), ('like-new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('for-parts', 'For Parts')], max_length=20)),
                ('category', models.IntegerField(help_text='Category ID (1=Properties, 2=Vehicles, 3=Electronics, etc)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('detailed_address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='sqft', max_length=20, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=10, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=10, null=True)),
                ('amenities', models.JSONField(blank=True, default=dict, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('mileage', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_year', models.CharField(blank=True, max_length=4, null=True)),
                ('electronics_type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('age_value', models.CharField(blank=True, max_length=10, null=True)),
                ('age_unit', models.CharField(blank=True, default='months', max_length=10, null=True)),
                ('warranty', models.CharField(blank=True, max_length=30, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale Post',
                'verbose_name_plural': 'Sale Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sale_posts/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sale.salepost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
