# Generated by Django 5.1.4 on 2025-05-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('stop', 'Stop'), ('sold', 'Sold'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
