# Generated by Django 5.1.4 on 2025-05-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_forsalecategory_id'),
        ('sale', '0002_alter_salepost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.forsalecategory'),
        ),
    ]
