# Generated by Django 5.1.4 on 2025-05-13 05:20

import django.db.models.deletion
import sale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_salepost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSaleBanner',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForSaleCategory',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='salepostimage',
            name='id',
            field=models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.forsalecategory'),
        ),
        migrations.CreateModel(
            name='ForSaleSubCategory',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subcategory_icons/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='sale.forsalecategory')),
            ],
        ),
    ]
