# Generated by Django 5.1.4 on 2025-05-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_forsalebanner_forsalecategory_alter_salepostimage_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salepostimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='salepostimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='salepostimage',
            name='sale_post',
        ),
        migrations.AddField(
            model_name='salepost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='sale_posts', to='sale.salepostimage'),
        ),
        migrations.AlterField(
            model_name='salepostimage',
            name='image',
            field=models.ImageField(upload_to='sale_posts_images/'),
        ),
    ]
