# Generated by Django 5.1.4 on 2025-05-13 12:19

import sale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_salecategory_salechildcategory_saleimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBanner',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='sale_banners/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sale Banner',
                'verbose_name_plural': 'Sale Banners',
                'ordering': ['order'],
            },
        ),
    ]
