# Generated by Django 5.1.4 on 2025-05-13 12:55

import django.db.models.deletion
import sale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_salebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCondition',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Brand New')", max_length=100)),
                ('value', models.CharField(help_text="Value for database (e.g., 'brand-new')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this condition', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the dropdown')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this condition is currently available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sale Condition',
                'verbose_name_plural': 'Sale Conditions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='salepost',
            name='condition',
            field=models.CharField(choices=[('brand-new', 'Brand New'), ('like-new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('for-parts', 'For Parts')], max_length=100),
        ),
        migrations.AddField(
            model_name='salepost',
            name='condition_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sale.salecondition', verbose_name='Condition'),
        ),
    ]
