# Generated by Django 5.1.4 on 2025-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_salecondition_alter_salepost_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='condition',
            field=models.CharField(max_length=100),
        ),
    ]
