# Generated by Django 5.1.4 on 2025-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_alter_salepost_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepost',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='detailed_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salepost',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
