# Generated by Django 5.1.4 on 2025-05-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_salepost_area_alter_salepost_detailed_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='sale.salecategory'),
        ),
    ]
