# Generated by Django 5.1.4 on 2025-06-19 06:29

import sale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_salebanner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSponsoredHorizontal',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('offer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('open_external', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='sale_sponsored_horizontals/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleSponsoredVertical',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('offer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('open_external', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='sale_sponsored_verticals/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
