# Generated by Django 5.0.1 on 2025-11-27 14:54

import django.db.models.deletion
import sale.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_salesponsoredhorizontal_salesponsoredvertical'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePostReport',
            fields=[
                ('id', models.BigIntegerField(default=sale.models.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('inappropriate', 'Inappropriate content'), ('duplicate', 'Duplicate listing'), ('fraud', 'Fraudulent'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sale.salepost')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sale_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale Post Report',
                'verbose_name_plural': 'Sale Post Reports',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reported_by')},
            },
        ),
    ]
