# Generated by Django 5.0 on 2026-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0013_salepostreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepost',
            name='delivery_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
