CITY_AREAS = {
    "Dhaka": [
        {"name": "Adabor"},
        {"name": "Badda"},
        {"name": "Banani"},
        {"name": "Bangshal"},
        {"name": "Bimanbondor"},
        {"name": "Cantonment"},
        {"name": "Chalkbazar"},
        {"name": "Dakshinkhan"},
        {"name": "Darus-Salam"},
        {"name": "Demra"},
        {"name": "Dhanmondi"},
        {"name": "Gandaria"},
        {"name": "Gulshan"},
        {"name": "Hazaribag"},
        {"name": "Jatrabari"},
        {"name": "Kafrul"},
        {"name": "Kalabagan"},
        {"name": "Kamrangirchar"},
        {"name": "Khilgaon"},
        {"name": "Khilkhet"},
        {"name": "Kadamtoli"},
        {"name": "Kotwali"},
        {"name": "Lalbagh"},
        {"name": "Mirpur Model"},
        {"name": "Mirpur"},
        {"name": "Mohammadpur"},
        {"name": "Motijheel"},
        {"name": "Mugda"},
        {"name": "New Market"},
        {"name": "Pallabi"},
        {"name": "Paltan"},
        {"name": "Ramna"},
        {"name": "Rampura"},
        {"name": "Rupnagar"},
        {"name": "Sabujbag"},
        {"name": "Shah Ali"},
        {"name": "Shahbagh"},
        {"name": "Shahjahanpur"},
        {"name": "Shyampur"},
        {"name": "Tejgaon"},
        {"name": "Sher-e-bangla"},
        {"name": "Tejgaon Shilpanchal"},
        {"name": "Turag"},
        {"name": "Uttara East"},
        {"name": "Uttara West"},
        {"name": "Uttarkhan"},
        {"name": "Vashantek"},
        {"name": "Vatara"},
        {"name": "Wari"}
    ]
}
