# Generated by Django 5.1.4 on 2025-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0002_alter_businessnetworkpostcomment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessnetworkmedia',
            name='post',
        ),
        migrations.AddField(
            model_name='businessnetworkpost',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessnetworkpost',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='business_network_posts', to='business_network.businessnetworkmedia'),
        ),
    ]
