# Generated by Django 5.1.4 on 2025-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0003_remove_businessnetworkmedia_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessnetworkposttag',
            name='post',
        ),
        migrations.AddField(
            model_name='businessnetworkpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='business_network_posts', to='business_network.businessnetworkposttag'),
        ),
    ]
