# Generated by Django 5.1.4 on 2025-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0004_remove_businessnetworkposttag_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNetworkWorkspace',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
