# Generated by Django 5.1.4 on 2025-04-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0007_alter_businessnetworkfollowermodel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnAdsPanelCategory',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbnAdsPanelMedia',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_network/abn/')),
                ('video', models.FileField(blank=True, null=True, upload_to='business_network/abn/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbnAdsPanel',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('BD', 'Bangladesh')], default='BD', max_length=2)),
                ('ad_type', models.CharField(choices=[('click_to_website', 'Click To Website'), ('call_on_whatsapp', 'Call On WhatsApp'), ('call_on_phone', 'Call On Phone'), ('email_us', 'Email Us')], default='image', max_length=20)),
                ('ad_budgert', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abn_ads_panel', to='business_network.abnadspanelcategory')),
                ('media', models.ManyToManyField(blank=True, related_name='abn_ads_panel', to='business_network.abnadspanelmedia')),
            ],
        ),
    ]
