# Generated by Django 5.1.4 on 2025-04-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0009_businessnetworkmindforcecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_network_mindforce', to='business_network.businessnetworkmindforcecategory'),
        ),
    ]
