# Generated by Django 5.1.4 on 2025-04-28 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0010_businessnetworkmindforce_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_network_mindforce', to=settings.AUTH_USER_MODEL),
        ),
    ]
