# Generated by Django 5.1.4 on 2025-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0011_businessnetworkmindforce_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
