# Generated by Django 5.1.4 on 2025-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0012_businessnetworkmindforce_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessnetworkmindforce',
            old_name='payment_method',
            new_name='payment_option',
        ),
    ]
