# Generated by Django 5.1.4 on 2025-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0013_rename_payment_method_businessnetworkmindforce_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('solved', 'Solved')], default='active', max_length=255, null=True),
        ),
    ]
