# Generated by Django 5.1.4 on 2025-04-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0014_businessnetworkmindforce_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforce',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='BusinessNetworkMindforceComment',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindforce_comments', to=settings.AUTH_USER_MODEL)),
                ('mindforce_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindforce_comments', to='business_network.businessnetworkmindforce')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
