# Generated by Django 5.1.4 on 2025-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0015_businessnetworkmindforce_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforcecomment',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
