# Generated by Django 5.1.4 on 2025-04-30 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0017_usersavedposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersavedposts',
            unique_together={('user', 'post')},
        ),
    ]
