# Generated by Django 5.1.4 on 2025-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0019_businessnetworknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('stoped', 'Stoped')], default='active', max_length=20),
        ),
    ]
