# Generated by Django 5.1.4 on 2025-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0020_abnadspanel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abnadspanel',
            old_name='ad_budgert',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
