# Generated by Django 5.1.4 on 2025-05-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0021_rename_ad_budgert_abnadspanel_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanel',
            name='estimated_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
