# Generated by Django 5.1.4 on 2025-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0022_abnadspanel_estimated_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnadspanel',
            name='country',
            field=models.CharField(choices=[('bangladesh', 'Bangladesh')], default='bangladesh', max_length=15),
        ),
    ]
