# Generated by Django 5.1.4 on 2025-05-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0023_alter_abnadspanel_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanel',
            name='user',
            field=models.ForeignKey(default='556fcc55-dfa3-4370-9870-f8662c55feae', on_delete=django.db.models.deletion.CASCADE, related_name='abn_ads_panel', to=settings.AUTH_USER_MODEL),
        ),
    ]
