# Generated by Django 5.1.4 on 2025-05-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0025_alter_abnadspanel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abnadspanel',
            name='gender',
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='ad_type_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
