# Generated by Django 5.1.4 on 2025-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0026_remove_abnadspanel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmindforcecomment',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='mindforce_comments', to='business_network.businessnetworkmindforcemedia'),
        ),
    ]
