# Generated by Django 5.1.4 on 2025-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0027_businessnetworkmindforcecomment_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNetworkMindforceCommentMedia',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_network/mindforce/comment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='businessnetworkmindforcecomment',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='mindforce_comments', to='business_network.businessnetworkmindforcecommentmedia'),
        ),
    ]
