# Generated by Django 5.1.4 on 2025-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0028_businessnetworkmindforcecommentmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnetworkpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessnetworkpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
