# Generated by Django 5.1.4 on 2025-05-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0029_alter_businessnetworkpost_content_and_more'),
    ]

    operations = [
    ]
