# Generated by Django 5.1.4 on 2025-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0031_fix_mindforce_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkpostcomment',
            name='diamond_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessnetworkpostcomment',
            name='is_gift_comment',
            field=models.BooleanField(default=False),
        ),
    ]
