# Generated by Django 5.1.4 on 2025-05-23 19:03

import business_network.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0032_businessnetworkpostcomment_diamond_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsorship Package',
                'verbose_name_plural': 'Sponsorship Packages',
            },
        ),
        migrations.CreateModel(
            name='GoldSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=business_network.models.sponsor_logo_path)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='business_network.sponsorshippackage')),
            ],
            options={
                'verbose_name': 'Gold Sponsor',
                'verbose_name_plural': 'Gold Sponsors',
                'ordering': ['-created_at'],
            },
        ),
    ]
