# Generated by Django 5.1.4 on 2025-10-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0035_alter_goldsponsorbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkpostcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='business_network.businessnetworkpostcomment'),
        ),
    ]
