# Generated by Django 5.1.4 on 2025-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0037_alter_businessnetworknotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
