# Generated by Django 5.1.4 on 2025-10-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0038_businessnetworkpost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnetworkmindforce',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_network_mindforce', to='business_network.businessnetworkmindforcecategory'),
        ),
    ]
