# Generated by Django 5.1.4 on 2025-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0039_alter_businessnetworkmindforce_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsponsor',
            name='profile_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goldsponsor',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goldsponsorbanner',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
