# Generated by Django 5.0.1 on 2025-12-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0040_alter_goldsponsor_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessnetworknotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Network Notification', 'verbose_name_plural': 'Business Network Notifications'},
        ),
    ]
