# Generated by Django 5.0.1 on 2026-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0041_alter_businessnetworknotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='business_network/thumbnails/'),
        ),
        migrations.AddField(
            model_name='businessnetworkmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='businessnetworkmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='business_network/videos/'),
        ),
    ]
