# Generated by Django 5.0.1 on 2026-01-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0042_businessnetworkmedia_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmedia',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
