# Generated by Django 5.0 on 2026-05-30 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0043_businessnetworkmedia_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessnetworkfollowermodel',
            index=models.Index(fields=['follower', 'following'], name='bn_follow_follower_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkfollowermodel',
            index=models.Index(fields=['following', 'follower'], name='bn_follow_following_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpost',
            index=models.Index(fields=['visibility', 'is_banned', '-created_at'], name='bn_post_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpost',
            index=models.Index(fields=['author', '-created_at'], name='bn_post_author_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpostcomment',
            index=models.Index(fields=['author', '-created_at'], name='bn_comment_author_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpostcomment',
            index=models.Index(fields=['post', 'author', '-created_at'], name='bn_comment_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpostlike',
            index=models.Index(fields=['user', '-created_at'], name='bn_like_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkpostlike',
            index=models.Index(fields=['post', 'user'], name='bn_like_post_user_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnetworkposttag',
            index=models.Index(fields=['tag'], name='bn_post_tag_tag_idx'),
        ),
    ]
