# Generated by Django 5.0 on 2026-06-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0046_backfill_feed_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSponsorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, default='', help_text='Division / State (e.g. Dhaka). Blank = any division.', max_length=128)),
                ('city', models.CharField(blank=True, default='', help_text='City / District. Blank = any city.', max_length=128)),
                ('area', models.CharField(blank=True, default='', help_text='Area / Upazila. Blank = any area.', max_length=128)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business_network.goldsponsor')),
            ],
            options={
                'verbose_name': 'Target location',
                'verbose_name_plural': 'Target locations',
            },
        ),
    ]
