# Generated by Django 5.0 on 2026-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0047_goldsponsorlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSponsorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_location_discount_percent', models.PositiveIntegerField(default=70, help_text='Discount % applied when a sponsor targets specific locations (vs all over Bangladesh).')),
                ('max_custom_locations', models.PositiveIntegerField(default=10, help_text='Maximum number of custom target locations a sponsor can add.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold Sponsor settings',
                'verbose_name_plural': 'Gold Sponsor settings',
            },
        ),
        migrations.AddField(
            model_name='goldsponsor',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
