# Generated by Django 5.0 on 2026-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0048_goldsponsorsettings_goldsponsor_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldsponsorsettings',
            name='max_discount_divisions',
            field=models.PositiveIntegerField(default=2, help_text='The discount applies only when the targeting covers at most this many distinct divisions. More divisions = full price.'),
        ),
    ]
