# Generated by Django 5.1.4 on 2026-06-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0049_goldsponsorsettings_max_discount_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldsponsor',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GoldSponsorReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('expiry_7d', 'Expires in 7 days'), ('expiry_3d', 'Expires in 3 days'), ('expiry_1d', 'Expires tomorrow'), ('autorenew_success', 'Auto-renewed'), ('autorenew_low', 'Auto-renew needs balance'), ('expired_notice', 'Expired notice'), ('winback', 'Win-back')], max_length=40)),
                ('channel', models.CharField(default='push', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='business_network.goldsponsor')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('sponsor', 'stage')},
            },
        ),
    ]
