# Generated by Django 5.0 on 2026-07-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0054_post_shared_from'),
        ('news', '0010_alter_breakingnews_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkpost',
            name='shared_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bn_reshares', to='news.newspost'),
        ),
    ]
