# Generated by Django 5.0 on 2026-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0055_businessnetworkpost_shared_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnetworkpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers only'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
