# Generated by Django 5.0 on 2026-07-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0056_alter_businessnetworkpost_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Fake or impersonating account'), ('spam', 'Spam or scam'), ('harassment', 'Harassment or hate speech'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Report',
                'verbose_name_plural': 'Profile Reports',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'reported_user', 'reason')},
            },
        ),
    ]
