# Generated by Django 5.0 on 2026-07-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0060_monetization_earnings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpv_rate', models.DecimalField(decimal_places=2, default=0.4, max_digits=6)),
                ('creator_share_percent', models.PositiveIntegerField(default=40)),
                ('admob_view_value', models.DecimalField(decimal_places=3, default=0.05, max_digits=6)),
                ('viewer_reward_enabled', models.BooleanField(default=True)),
                ('views_per_diamond', models.PositiveIntegerField(default=20)),
                ('max_daily_diamonds', models.PositiveIntegerField(default=5)),
                ('daily_frequency_cap', models.PositiveIntegerField(default=4)),
                ('interest_decay_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ads System Config',
            },
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='placements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abnadspanel',
            name='status',
            field=models.CharField(choices=[('review', 'In Review'), ('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('stoped', 'Stoped'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='UserAdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_weights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('panel', 'Ads Panel'), ('admob', 'AdMob')], default='panel', max_length=10)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('cta_click', 'CTA Click')], max_length=15)),
                ('placement', models.CharField(blank=True, default='', max_length=30)),
                ('platform', models.CharField(blank=True, default='app', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='business_network.abnadspanel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to='business_network.abnadspanelcategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ad_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='adevent_user_idx'), models.Index(fields=['creator', '-created_at'], name='adevent_creator_idx'), models.Index(fields=['ad', '-created_at'], name='adevent_ad_idx'), models.Index(fields=['created_at'], name='adevent_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdViewerDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('diamonds_awarded', models.PositiveIntegerField(default=0)),
                ('rewarded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_viewer_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'rewarded'], name='adviewer_date_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CreatorAdEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('panel_views', models.PositiveIntegerField(default=0)),
                ('admob_views', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_ad_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('creator', 'date')},
            },
        ),
    ]
