# Generated by Django 5.0 on 2026-07-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0061_adssystemconfig_abnadspanel_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanel',
            name='boosted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='business_network.businessnetworkpost'),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='companion_banner',
            field=models.ImageField(blank=True, null=True, upload_to='business_network/abn/banners/'),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='format',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('boost', 'Boosted Post')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='target_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
