# Generated by Django 5.0 on 2026-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0062_abnadspanel_boosted_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradprofile',
            name='brain_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradprofile',
            name='gender_affinity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='useradprofile',
            name='interest_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='useradprofile',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
