# Generated by Django 5.0 on 2026-07-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0063_useradprofile_brain_built_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adssystemconfig',
            name='cpv_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
