# Generated by Django 5.0 on 2026-07-24 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0064_adssystemconfig_cpv_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adevent',
            name='content_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adssystemconfig',
            name='creator_share_percent',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['creator', 'content_id'], name='adevent_content_idx'),
        ),
    ]
