# Generated by Django 5.0 on 2026-07-24 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0065_adevent_content_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanel',
            name='ad_objective',
            field=models.CharField(choices=[('engagement', 'Engagement'), ('retargeting', 'Retargeting'), ('announcement', 'Announcement')], default='engagement', max_length=15),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='retarget_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='retarget_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='abnadspanel',
            name='target_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event_burst', 'Ad event burst'), ('ctr_anomaly', 'Abnormal CTR'), ('reward_pump', 'Viewer reward pumping'), ('self_view', 'Advertiser self-viewing'), ('balance_anomaly', 'Balance anomaly'), ('spam', 'Spam behaviour')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('emailed', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='fraud_kind_idx')],
            },
        ),
    ]
