# Generated by Django 5.0 on 2026-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0066_abnadspanel_ad_objective_abnadspanel_retarget_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkmedia',
            name='video_original',
            field=models.FileField(blank=True, null=True, upload_to='business_network/videos/originals/'),
        ),
    ]
