# Generated by Django 5.0 on 2026-07-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0067_businessnetworkmedia_video_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessnetworkmedia',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
