# Generated by Django 5.0 on 2026-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0068_alter_businessnetworkmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnadspanel',
            name='ad_type',
            field=models.CharField(choices=[('click_to_website', 'Click To Website'), ('call_on_whatsapp', 'Call On WhatsApp'), ('call_on_phone', 'Call On Phone'), ('email_us', 'Email Us'), ('message_on_adsyconnect', 'Message on AdsyConnect')], default='image', max_length=30),
        ),
    ]
