# Generated by Django 5.1.4 on 2026-07-27 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0070_alter_abnadspanel_ad_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevent',
            name='event_type',
            field=models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('cta_click', 'CTA Click'), ('lead', 'Lead')], max_length=15),
        ),
        migrations.CreateModel(
            name='AbnAdLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.CharField(blank=True, default='', max_length=64)),
                ('first_message', models.TextField(blank=True, default='')),
                ('last_message', models.TextField(blank=True, default='')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='business_network.abnadspanel')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_leads_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_leads_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['advertiser', '-last_message_at'], name='adlead_advertiser_idx'), models.Index(fields=['ad', '-last_message_at'], name='adlead_ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('ad', 'sender'), name='uniq_ad_lead_per_sender')],
            },
        ),
    ]
