# Generated by Django 5.0 on 2026-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0071_alter_adevent_event_type_abnadlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnetworkpostcomment',
            name='mentioned_users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
