# Generated by Django 5.0 on 2026-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0072_businessnetworkpostcomment_mentioned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='adssystemconfig',
            name='admob_share_percent',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
