# Generated by Django 5.0 on 2026-07-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0073_adssystemconfig_admob_share_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnadspanelmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='business_network/abn/thumbnails/'),
        ),
    ]
