# Generated by Django 5.0 on 2026-07-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network', '0074_abnadspanelmedia_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnadspanel',
            name='ad_type',
            field=models.CharField(choices=[('click_to_website', 'Click To Website'), ('shop_now', 'Shop Now'), ('call_on_whatsapp', 'Call On WhatsApp'), ('call_on_phone', 'Call On Phone'), ('email_us', 'Email Us'), ('message_on_adsyconnect', 'Message on AdsyConnect'), ('none', 'No button')], default='image', max_length=30),
        ),
    ]
