# Codemagic CI/CD Configuration for AdsyClub iOS App
# Documentation: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: AdsyClub App Store Connect
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.adsyclub.app
      groups:
        - firebase_credentials
      vars:
        APP_ID: "YOUR_APP_STORE_APP_ID"  # Replace with your App Store App ID
        BUNDLE_ID: "com.adsyclub.app"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Clean CocoaPods cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
      
      - name: Set up Firebase configuration
        script: |
          # Copy GoogleService-Info.plist from environment variable
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos || true
      
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=8.0.8 \
            --build-number=$((${PROJECT_BUILD_NUMBER:-39})) \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        
        # Optional: Automatically submit for review
        # submit_to_app_store: true
        # cancel_previous_submissions: true
        # release_type: SCHEDULED
        # earliest_release_date: 2024-01-01T00:00:00+00:00

  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: AdsyClub App Store Connect
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.adsyclub.app
      groups:
        - firebase_credentials
      vars:
        BUNDLE_ID: "com.adsyclub.app"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Clean CocoaPods cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
      
      - name: Set up Firebase configuration
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=8.0.8 \
            --build-number=$((${PROJECT_BUILD_NUMBER:-39})) \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.adsyclub.app
      groups:
        - firebase_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      
      - name: Set up Firebase configuration
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos || true
      
      - name: Build iOS (Debug)
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: false
          failure: true
